Botón para descargar el código de un envío y sus tests
emartinm/lsql pull request #18
Opened 2020-12-04 19:44 UTC by Tamiflu9

No se si los test estarán bien, pero no me saltan errores..

Al comprobar el pylint me daba un 9.99/10 y he añadido dos cosas para que no me salieran los mensajes de error y conseguir el 10/10. No se si he hecho bien.

2020-12-05 00:01 UTC, emartinm commented
Me resulta imposible revisar un PR que dice haber modificado 37 ficheros :-( Sobre todo porque el 95% de los cambios que dice tener no son tuyos, y es una auténtica locura. Otra cosa que tendrías que corregir son los conflictos en lsql/judge/tests/test_views.py.

Creo que algo mal estamos haciendo en la manera en la que actualizáis vuestro fork con los cambios del upstream. Porque antes de hacer el PR actualizas los ficheros de tu repositorio a partir del principal y fusionas los cambios, ¿verdad? ¿Podrías decirme qué comandos ejecutas para actualizar tu repositorio fork con los cambios del repositorio principal?

2020-12-05 11:33 UTC, Tamiflu9 commented
No uso comandos, me descargue una aplicación: Github-Desktop, que parecía más fácil de usar pero igual no lo estoy haciendo bien. He probado ahora a hacerlo con comandos clonando el repositorio otra vez y todo y no me deja actualizar mi repositorio. 
He usado estos comandos:

$ git clone https://github.com/Tamiflu9/lsql.git
$ cd lsql
$ git remote add upstream https://github.com/emartinm/lsql.git
$ git fetch upstream
$ git rebase upstream/master

-- aqui me da un error el TODO.md

error: could not apply 4e10dcf... Update TODO.md
CONFLICT (content): Merge conflict in TODO.md

y luego a la hora de actualizar no hace nada.
$ git push -f origin master

2020-12-05 22:27 UTC, emartinm commented
Resolviste al final el conflicto con TODO.md, @Tamiflu9 ? Es que ahora me aparece un nuevo commit mucho más manejable, que podría revisar. ¿Hiciste algo concreto?

2020-12-06 00:06 UTC, Tamiflu9 commented
al cambiar el test_view.py y resolver los conflictos me pedía hacer un commit y después de hacerlo ahi si que me parecían solo mis cambios (y no como antes que salían todos los que se habían hecho hasta el momento) y no se si ha sido eso lo que ha cambiado, porque no he hecho nada mas creo...

2020-12-06 12:50 UTC, emartinm requested changes
Además de los comentarios de cada fichero PY, hay 5 o 6 ficheros SH que han cambiado su modo de 100755 a 100644. Seguramente lo has cambiado sin darte cuenta, pero es imprescidible que los devuelvas al 100755 porque deben ser ejecutables. Si no, el sistema de integración continua no puede realizar su trabajo y pasar todos los tests ni pylint.

2020-12-06 12:50 UTC, emartinm commented on lsql/.pylintrc
> +disable=
Para conseguir un 10 en pylint hay que cumplir todas los requisitos que pide, no deshabilitar comprobaciones. En este caso deberás añadir el docstring a las clases y módulos que lo necesiten.

2020-12-06 12:50 UTC, emartinm commented on lsql/judge/templates/submission.html
> +                <a href="{% url 'judge:download_submission' submission.id %}" download_submission="code.sql" >
En los comentarios PR incluid capturas de pantalla de los nuevos elementos visuales y páginas generadas para que las veamos.

2020-12-06 12:50 UTC, emartinm commented on lsql/judge/templates/submission.html
> +                <a href="{% url 'judge:download_submission' submission.id %}" download_submission="code.sql" >
¿Exactamente qué es lo que hace el <<download_submission="code.sql">>?

2020-12-06 12:50 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        # download_submission from different user
No queremos tests condicionales para que se ejecute uno u otro, queremos dos tests:

1. Uno con el usuario 'pepe', que es el que ha creado submission. En este caso debe obtener el fichero code.sql **y su contenido debe ser igual que el submission**
1. Otro con el usuario 'ana', que debe ser prohibido

De hecho te recomiendo que saques tus comprobaciones de test_logged() y crees un nuevo método test_download_submission() donde pruebes estos dos casos (creando los usuarios, problemas y envíos). Así queda separado, será más claro y te liarás menos. Puedes inspirarte en test_download() de Iker.

2020-12-06 12:50 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +            self.assertEqual(response.status_code, 'Forbidden')
Hasta donde yo imagino, los código de estado **son números**

2020-12-06 12:50 UTC, emartinm commented on lsql/judge/views.py
> +@login_required
Este método download_submission() es el mismo que aparece justo debajo, de hecho es una aportación de Iker. No debería aparecer en tu commit

2020-12-06 12:52 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +            self.assertEqual(response.status_code, 'Forbidden')
(En tu caso comparas con 'Forbidden' y no estoy seguro de que funcione)

2021-02-21 21:52 UTC, emartinm commented
Cerrado porque es muy antiguo y se hará uno nuevo desde cero.

2021-02-21 21:52 UTC, closed without merging