Boton para colapsar tablas añadido
emartinm/lsql pull request #27
Opened 2021-02-22 19:16 UTC by ivarui01

2021-02-22 20:41 UTC, emartinm commented
Como los cambios son 100% en el frontend no se va a probar nada de manera automática con los tests de unidad. Por eso necesito que incluyas un pequeño video capturando la pantalla y donde pueda ver cómo se muestran y cómo se comportan las tablas **en todos las páginas que las usan**. Son unas pocas, porque es una función bastante útil:

![Captura de pantalla de 2021-02-22 21-40-15](https://user-images.githubusercontent.com/1685343/108767420-b5a41a00-7556-11eb-86f8-3e3d4a05bc54.png)

2021-02-24 18:46 UTC, emartinm commented
Como hemos comentado hoy, faltaría:
- Que el botón colapse únicamente las filas de la tabla, no su cabecera
- Estudiar si el botón puede cambiar de + a - de manera estable
- Cuando todo esté resuelto, añadir capturas para ver que funciona bien. Aunque la idea de no añadir botón a las tablas sin nombre es muy buena, porque así limita bastante interacciones no deseadas

2021-02-25 19:48 UTC, ivarui01 reviewed
He cambiado la funcionalidad del botón para que al colapsar las tablas siga apareciendo la cabecera. Además he intentado hacer que el botón cambie de "+" a "-" o al revés al ser pulsado y he conseguido que funcione bien para todos los botones y no solo algunos como te enseñé, pero el problema es que al estar en funciones diferentes, el cambio de texto (función JS mía) y el colapsar (función de Bootstrap), si le das muy rápido al botón, el texto cambia tan rápido como lo presiones, pero la función colapsar tarda un poco más en ejecutarse por lo tanto puede haber incoherencias (en el botón aparece un "-" estando la tabla colapsada o un "+" estando la tabla sin colapsar) por lo tanto no he añadido la funcionalidad del cambio de símbolo. Adjunto también las capturas en donde show_table.html es usada.
![feedback_ce](https://user-images.githubusercontent.com/61693814/109208482-a7e6d280-77aa-11eb-9d14-0e2f35169d13.PNG)
![feedback_wa_missing_rows](https://user-images.githubusercontent.com/61693814/109208485-a87f6900-77aa-11eb-8c70-b93f8f07935a.PNG)
![feedback_wa_order](https://user-images.githubusercontent.com/61693814/109208486-a87f6900-77aa-11eb-8405-8f0045d986ea.PNG)
![feedback_wa_wrong_rows](https://user-images.githubusercontent.com/61693814/109208488-a917ff80-77aa-11eb-8fa0-7f05a56627a0.PNG)
![problem_dml](https://user-images.githubusercontent.com/61693814/109208490-a917ff80-77aa-11eb-9ca7-2a1eaa37e6ce.PNG)
![problem_function](https://user-images.githubusercontent.com/61693814/109208492-a917ff80-77aa-11eb-9c00-4373577922b1.PNG)
![problem_proc](https://user-images.githubusercontent.com/61693814/109208495-a9b09600-77aa-11eb-90d9-f6593c3878e2.PNG)
![problem_trigger](https://user-images.githubusercontent.com/61693814/109208497-a9b09600-77aa-11eb-92e8-bf861fcacd7a.PNG)

2021-02-26 09:53 UTC, emartinm requested changes
Lo del cambio de texto es una pena pero bueno, tampoco es que fuera algo especialmente imprescindible. Te propongo un par de cambios de 1 línea y cuando los tengas podría aceptar el PR.

2021-02-26 09:53 UTC, emartinm commented on lsql/judge/templates/show_table.html
> +    <button class="btn btn-light btn-outline-secondary ml-3 mb-3" data-toggle="collapse" data-target="#table-{{ id }}">+</button>
Para que el botón sea un poquito más pequeño y salga en color azul (creo que es lo mejor, por uniformidad) utiliza mejor estas clases:

    class="btn btn-primary btn-sm ml-3 mb-3"

2021-02-26 09:53 UTC, emartinm commented on lsql/judge/templates/show_table.html
> +    <tbody class="collapse show" id="table-{{ id }}">
Quizá a la larga nos damos cuenta de que no es la mejor opción, pero por ahora haz que las tablas se muestren colapsadas por defecto y que únicamente se vean las filas cuando se pulse el botón

2021-02-26 18:54 UTC, ivarui01 commented
Ya he subido los nuevos cambios.
![image](https://user-images.githubusercontent.com/61693814/109342569-599a0800-786c-11eb-893e-cacb183a0abb.png)

2021-02-26 19:01 UTC, emartinm commented
Perfecto, muchas gracias. PR terminado e integrado

2021-02-26 19:01 UTC, merged