Nuevas propuestas de funcionalidades
emartinm/lsql pull request #4
Opened 2020-09-24 13:53 UTC by Dashito14

Soy Daniel Ibáñez, he añadido algunas propuestas de funcionalidades nuevas. Están escritas de forma esquemática, en la próxima reunión las explicaré mejor.

2020-09-24 14:10 UTC, emartinm commented
Tus aportaciones son muy interesantes, Daniel. Y me gusta que hayas probado a hacer un Pull Request con éxito :+1: 

Te he dejado un comentario para que fusiones una entrada que propones con otra de JC. Además así aprendemos los dos cómo manejar un Pull Request con comentarios, que será algo bastante común.

2020-09-24 14:30 UTC, emartinm commented
Deberías poder verlo en la propia página del Pull Request, tanto en "Conversation" como en "Files Changed". La página de este Pull Request es https://github.com/emartinm/lsql/pull/4

2020-09-24 15:53 UTC, Dashito14 commented
He entrado a la pestaña de "Files Changed" y he habilitado "Ver comentarios" y no soy capaz de encontrarlo :( Es la primera vez que utilizo esto y no sé bien como verlo.

2020-09-24 16:12 UTC, emartinm requested changes
He dejado un mensaje concreto en la línea que necesitaría ser fusionada, espero que ahora lo puedas ver.

2020-09-24 16:14 UTC, emartinm commented
> He entrado a la pestaña de "Files Changed" y he habilitado "Ver comentarios" y no soy capaz de encontrarlo :( Es la primera vez que utilizo esto y no sé bien como verlo.

También es la primera vez que yo gestiono un repositorio GitHub recibiendo PR, y la culpa era mía porque no había pulsado el botón para publicar la revisión de manera definitiva :-s Perdón por volverte loco innecesariamente

2020-09-24 16:33 UTC, Dashito14 commented on TODO.md
> +* (DI) Traducción a otros idiomas de España como el valenciano.
Vale, me parece correcto, para corregirlo ¿hago otro pull request?

2020-09-24 16:41 UTC, emartinm commented on TODO.md
> +* (DI) Traducción a otros idiomas de España como el valenciano.
Creo (no estoy 100% seguro) que con que hagas _push_ de los nuevos cambios en tu fork, GitHub debería darse cuenta automáticamente y actualizar el PR con un nuevo _commit_. Prueba a ver qué tal.

2020-09-24 19:31 UTC, Dashito14 commented on TODO.md
> +* (DI) Traducción a otros idiomas de España como el valenciano.
Creo que sí, he hecho el push y se ha cambiado aquí automáticamente

2020-09-25 09:16 UTC, merged

2020-09-25 09:19 UTC, emartinm commented
Nos ha costado un poco, @Dashito14 , pero ha salido perfecto :+1: