Fechas resultados
emartinm/lsql pull request #42
Opened 2021-03-06 15:49 UTC by iburgoa13

2021-03-06 21:38 UTC, emartinm commented
Voy revisando el código, pero te quería pedir que añadieses algunas capturas de pantalla que quede documentado cómo se muestran los nuevos rankings

2021-03-06 21:45 UTC, iburgoa13 commented
Lo tengo anotado! No te preocupes, debí ponerlo, lo subí y me tuve que ir, mañana por ls mañana subo si eso algún cambio que me. Digas y todas las fotos con las vistas.

2021-03-06 22:27 UTC, emartinm requested changes
El fichero ` lsql/judge/static/judge/js/result.js` no debería tener ningún cambio, pero aparece aquí con 0 líneas cambiadas. ¿Se ha modificado sus permisos? Mejor reviértelo.

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        last_end_date = datetime.datetime.today() - timedelta(days=1)
Esto entra en conflicto con la comprobación de que la fecha start sea como mínimo el 1 de septiembre del curso actual respecto al día **en el que se ejecuta este test**. Entre replicabilidad de tests y esta comprobación, yo prefiero la replicabilidad. Piensa a ver si se te ocurre una manera de tener tests replicables con fechas fijas y tener la comprobación de inicio de curso.

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        self.assertIn('¡Error! La fecha desde no puede ser mayor que la fecha hasta.',
Cambia el mensaje:

    ¡Error! La fecha inicial no puede ser mayor que la fecha final.

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        self.assertIn(f"Por favor, la fecha desde mínimo debe ser {start}", response.content.decode('utf-8'))
En los mensajes generados, cambia "fecha desde" por "fecha inicial" y "fecha hasta" por "fecha final"

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        self.assertIn("¡Cuidado! Formato de fechas incorrectas.", response.content.decode('utf-8'))
"Formato incorrecto de fechas"

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        self.assertIn("¡Cuidado! Formato de fechas incorrectas.", response.content.decode('utf-8'))
Lo mismo

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        self.assertIn("¡Cuidado! Ha eliminado una de las fechas, la página no existe.",
"Es necesario proporcionar tanto la fecha inicial como la fecha final"

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +import datetime
Fusiona en un import, como antes

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +def first_day_of_course():
No entiendo, esta función es igual que `create_start_course`? Debería existir esta únicamente, y recibir una fecha como parámetro para devolver el primer día del curso **de ese día**

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +    """Returned on the first day of the academic year"""
"Returns the first day..."

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +    if 'time data ' in err.__str__():
`err.__str__()` es la invocación fea de de `str(err)`, mejor usa la segunda

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +    if 'time data ' in err.__str__():
Explica un poco en el docstring qué es `err`. Parece una excepción, si es así indícalo con claridad

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +                                 f"Por favor, la fecha desde mínimo debe ser {from_classification}"
mismo comentario sobre "fecha desde" y "fecha hasta", revísalo en todos tus cambios

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +        up_to_classification_date = None
Por qué necesitas inicializarlas a None si luego las asignas?

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +            parse_datetime(start)
Queda extraño parsear algo y no hacer nada con el resultado, añade un comentario indicando que lo que estás haciendo es **comprobar que son correctas**

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +                                                    'to_fixed': up_to_classification,
Qué diferencia hay entre las versiones 'date' y las versiones 'fixed'?

2021-03-06 22:27 UTC, emartinm commented on lsql/judge/views.py
> +                                                    'to_fixed': up_to_classification,
Uno es fecha y otro str? No te sirve únicamente una de ellas?

2021-03-07 09:22 UTC, iburgoa13 commented
Van las fotos:
Vista principal del profesor al entrar a Resultados a una colección.
![imagen](https://user-images.githubusercontent.com/43571438/110235011-0ee45400-7f2e-11eb-8d7f-e9c9cfc10015.png)
La primera fecha es 1 de septiembre del año que se introduzca y hasta la fecha de hoy.
Vista principal del alumno al entrar a Resultados a una colección.
![imagen](https://user-images.githubusercontent.com/43571438/110235040-32a79a00-7f2e-11eb-9740-830950ad784e.png)
Detalles: la url, no cambia para la vista del alumno y no salen fechas.
Un alumno intenta acceder a la url con fechas
![imagen](https://user-images.githubusercontent.com/43571438/110235059-4fdc6880-7f2e-11eb-8ed3-84cf17c61543.png)
Un alumno intenta acceder a la url con fechas de sus envios
![imagen](https://user-images.githubusercontent.com/43571438/110235078-6682bf80-7f2e-11eb-9555-d0c6b1e9ca83.png)
Cuando se pone fechas que no corresponden al curso.
![imagen](https://user-images.githubusercontent.com/43571438/110235115-b5c8f000-7f2e-11eb-9031-c0f6188cdc19.png)
Cuando pones fechas por url que no corresponden al curso (inicio la primera final la siguiente)
![imagen](https://user-images.githubusercontent.com/43571438/110235133-ca0ced00-7f2e-11eb-9885-febf4c4a7f25.png)
![imagen](https://user-images.githubusercontent.com/43571438/110235143-d4c78200-7f2e-11eb-8022-16121928a868.png)
Fechas invertidas
![imagen](https://user-images.githubusercontent.com/43571438/110235167-ea3cac00-7f2e-11eb-96c6-75a8f5b8fcd5.png)
Formato de fechas incorrectas
![imagen](https://user-images.githubusercontent.com/43571438/110235190-faed2200-7f2e-11eb-969f-a68f4df1d76d.png)
Cuando falta alguna fecha
![imagen](https://user-images.githubusercontent.com/43571438/110235200-093b3e00-7f2f-11eb-8571-a9f27b471d24.png)

2021-03-07 09:30 UTC, iburgoa13 commented
Me faltaban.
Ejercicios con filtro.
![imagen](https://user-images.githubusercontent.com/43571438/110235324-bb730580-7f2f-11eb-8a5b-ba8fb0e8f44f.png)
Envios con fecha inicio primer dia y fin dia actual (ej4)
![imagen](https://user-images.githubusercontent.com/43571438/110235368-efe6c180-7f2f-11eb-93dc-b66a3c3bf6d7.png)
Envios con fecha inicio primer dia y fin 17 de febrero (ej4)
![imagen](https://user-images.githubusercontent.com/43571438/110235413-1c9ad900-7f30-11eb-81da-403ea4af337e.png)

2021-03-07 10:28 UTC, emartinm commented
Otro comentario del que no me día cuenta ayer: **la validación de entradas del usuario en Django se realiza mediante formularios** (formularios Django, que son clases Python, no formularios HTML). Tus vistas reciben varios argumentos y algunos de ellos se validan (las fechas) y otro no. Es importante **validar todos los argumentos y que el proceso de validación esté encapsulado en un formulario** para que todas las validaciones estén en el mismo lugar y un desarrollador sepa dónde buscar. Aparte, los formularios proporcionan validaciones por defecto que casi siempre son las que necesitas para cada campo.

- Puedes ver un ejemplo de uso de formulario Django para validar en esta línea y las siguientes: https://github.com/emartinm/lsql/blob/5ae4aa21ac67ed040713a9a30d74c867d9bf6cf3/lsql/judge/views.py#L272 (en este caso con valores POST, pero será lo mismo con valores GET)
- La documentación de Django: https://docs.djangoproject.com/en/3.1/topics/forms/ es muy completa. Te interesará más la parte de definir el formulario y validar la entrada, no tanto renderizar el formulario HTML (aunque quizá también). En https://docs.djangoproject.com/en/3.1/ref/forms/fields/ verás todos los tipos de campos disponibles, donde hay varios para fechas.
- En las transparencias de Django que os envié hace unas semanas también hay ejemplo de validación con formularios.

Este comentario también es importante para @Tamiflu9 , @ivarui01 y @Dashito14 si en alguna tarea recibís argumentos POST o GET --> **hay que validar todos los argumentos que reciba la vista y en Django la manera unificada de manejar los argumentos son los formularios**

2021-03-07 11:38 UTC, iburgoa13 commented
Hola Enrique, he estado viendo cómo funciona todo eso, pero no entiendo, estoy espeso, ¿No se puede validar cómo ya se hace? Los grupos y fechas si se validan, está todo validado.
Además, me supone un impedimento porque he estado probando y esto significa ya sea añadir un if más o un return más y mi función está ya al máximo y el pylint no me deja hacer nada y seguramente todo esto cambien los test.
Pero estaría todo validado en principio.

2021-03-08 10:18 UTC, emartinm commented
> Hola Enrique, he estado viendo cómo funciona todo eso, pero no entiendo, estoy espeso, ¿No se puede validar cómo ya se hace? Los grupos y fechas si se validan, está todo validado.

Sí, eso no lo pongo en duda. Lo único que pretendo es que las validaciones se hagan usando los mecanismos estándar de Django para validar entradas del usuario, porque es donde un desarrollador (en este caso yo) esperaría que estuvieran. Y esto ayuda mucho a mantener el código que tenerlo desperdigado en 2 sitios posibles.

> Además, me supone un impedimento porque he estado probando y esto significa ya sea añadir un if más o un return más y mi función está ya al máximo y el pylint no me deja hacer nada y seguramente todo esto cambien los test.

Validar un formulario usa una sentencia mientras que tú usas dos para validar las dos fechas. Generar un mensaje de error con la validación fallida del formulario es una o dos sentencias, que es exactamente lo que gastas capturando la excepción de `parse_date`. Creo que desde el punto de vista de número de sentencias de tu vista no incrementa e incluso decrece. Y desde el punto de vista de los tests no cambiará nada si la validación realiza las mismas comprobaciones, que es el objetivo. Si las fechas no tienen el formato correcto o start es posterior a end tu vista debe generar lo mismo, independientemente del mecanismo usado para validar la entrada (comprobación en la vista o en un formulario).

2021-03-08 10:21 UTC, emartinm commented
Muchas gracias por las capturas de pantalla, son muy muy completas. Visualmente creo que está perfecto (no sé si @jcorreas tendrá algún comentario) y el comportamiento de los mensajes de error es el adecuado.

2021-03-08 10:31 UTC, emartinm commented on lsql/judge/views.py
> +def first_day_of_course():
Perfecto, lo único que no encuentro es un test concreto para la función `first_day_of_course`. ¿Me puedes indicar la línea donde está o el nombre que tiene ese test?

2021-03-08 10:32 UTC, emartinm commented on lsql/judge/views.py
> +    if 'time data ' in err.__str__():
Perfecto, ahora queda mucho más claro. ¡Gracias!

2021-03-08 10:37 UTC, iburgoa13 commented
Vale.. Luego si puedo hecho un vistazo bien a todo.. espero tenerlo hoy.

2021-03-08 10:48 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        response = client.get(classification_url, {
El cambio a poner fechas concretas es un paso muy bueno porque ahora los envíos de la BD y las peticiones que se realizan son independientes del día en el que se ejecute el test. Pero mi pregunta es: ¿qué pasará cuando lance los tests el día 5 de septiembre de 2021? No es algo extraño, de hecho espero que en septiembre siga añadiendo cosas. El tests usará `start` como "2020-9-1" que está fuera del curso académico actual. Entiendo que a partir de ese día los tests fallarán porque start no es válido.

Por eso veo que comprobar que la fecha start cae en el curso actual y tener tests 100% replicables independientes del día de ejecución entra en conflicto. Ló unico que se me ocurre para tener lo mejor de los dos mundos es:
1) que la página que ve el profesor cuando accede al ranking sea con start = 1 de septiembre del año actual. Como tenemos test para la función que calcula el primer día de curso, estamos seguros de que se calcula bien. Y desde el punto de vista de usabilidad, le estamos dando la vista que más sentido tiene, la del curso actual.
2) desactivar la comprobación, es decir, que poner un start anterior al curso actual no genere error. Esto nos permite que los tests envejezcan sin problema. Si algún profesor elige una fecha anterior, que no es lo normal, pues obtendrá unos resultados con más o menos sentido y utilidad. **¿Hay algo en tu código que filtra submissions que haga que únicamente funcione el curso actual?** Porque conceptualmente filtrar en un rango es independiente de las fechas y creo que quitar quitar la comprobación no debe romper nada.

2021-03-08 10:56 UTC, iburgoa13 commented
Hola Enrique, no, si es esa fecha te sale 1 de Septiembre de 2021, si es a lo que te refieres, ¿ o no? Me he perdido...
Acabo de hacer un test para la función, ¿Esto sirve? Y metí lo de 5 de Septiembre de 2021, sale 1 de Septiembre de ese año
![imagen](https://user-images.githubusercontent.com/43571438/110312376-4bcf4a00-8005-11eb-8589-f21d565b59e6.png)

2021-03-08 11:01 UTC, jcorreas commented on lsql/judge/tests/test_views.py
> +        response = client.get(classification_url, {
Muy bien todo lo anterior, incluidas las capturas de pantalla. Creo que ya lo tiene todo. Respecto al último mensaje de Enrique sobre los problemas al lanzar tests el 5 de septiembre de 2021, me parece bien la propuesta. Solo una observación: en 1, "... con start = 1 de septiembre del año actual.". No me queda claro este caso, ¿qué ocurre si el profesor accede al ranking el 31 de agosto de 2021, coge 1 de septiembre de 2021? (es más una duda, que con tanto mensaje ya no tengo nada claro).
Respecto a 2, me parece perfecto.

2021-03-08 11:03 UTC, jcorreas commented
(perdón, se ha cruzado mi mensaje con el de Iker, pero creo que los dos tenemos la misma duda :-)

2021-03-08 11:08 UTC, emartinm commented
> Hola Enrique, no, si es esa fecha te sale 1 de Septiembre de 2021, si es a lo que te refieres, ¿ o no? Me he perdido...

A ver si me explico mejor:
En la línea 400 de test_views.py se establece `start = first_day_of_course(datetime(2020, 9, 1))` y luego `end = datetime(2021, 3, 7).strftime('%Y-%m-%d')`. En la línea 441 se realiza la llamada `response = client.get(classification_url, {'start': start, 'end': end}, follow=True)`. Si yo ejecuto esto el 5 de septiembre de 2021, start será 2020-09-01 que es del curso pasado. En las líneas 443-447 se comprueban distintas cosas que debe contener la contestación, pero según veo en la línea 103 de views.py en ese caso la vista contendrá únicamente ` Ha insertado una fecha que no corresponde al año académico` y por tanto fallarán todas esas comprobaciones.

> Acabo de hacer un test para la función, ¿Esto sirve? Y metí lo de 5 de Septiembre de 2021, sale 1 de Septiembre de ese año
> ![imagen](https://user-images.githubusercontent.com/43571438/110312376-4bcf4a00-8005-11eb-8589-f21d565b59e6.png)

Exacto, esos son los tests que esperaba para esa función. ¿Podrías poner algún valor "extremo" como 29 de febrero de año bisiesto y fechas de años pasados y futuros?

2021-03-08 11:09 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        response = client.get(classification_url, {
Perdón, he usado "año actual" cuando me refería a "curso académico actual"

2021-03-08 11:16 UTC, iburgoa13 commented
Ah, vale, no deberían fallar Enrique, los envíos de los ejercicios cambio las fechas , entonces SI están dentro de ese filtro y no fallaría.
![imagen](https://user-images.githubusercontent.com/43571438/110314419-1841ef00-8008-11eb-963b-45d9cf8afac7.png)
Así vale? Añadí un año bisiesto y años siguientes y anteriores.

2021-03-08 11:22 UTC, iburgoa13 commented
Acabo de cambiar lo de la fecha inicio, ya se puede insertar la fecha inicio que se quiera, pasan los test correctamente.
Lo único , fecha MAXIMA si o si es dia de hoy, anterior deja todo y todo ok.
En principio solo me falta lo del forms @emartinm .

2021-03-08 11:33 UTC, emartinm commented
> Ah, vale, no deberían fallar Enrique, los envíos de los ejercicios cambio las fechas , entonces SI están dentro de ese filtro y no fallaría.
> ![imagen](https://user-images.githubusercontent.com/43571438/110314419-1841ef00-8008-11eb-963b-45d9cf8afac7.png)
> Así vale? Añadí un año bisiesto y años siguientes y anteriores.

¡Perfectísimo!

> Acabo de cambiar lo de la fecha inicio, ya se puede insertar la fecha inicio que se quiera, pasan los test correctamente.
> Lo único , fecha MAXIMA si o si es dia de hoy, anterior deja todo y todo ok.

Sí, eso impide realizar tests con rangos del futuro pero no lo veo problema. Lo importante para mi era tener tests que fueran exactamente iguales siempre y que devolvieran el mismo resultado independientemente de la fecha en la que se ejecuten.

Cuando tengas el commit lo reviso y voy resolviendo los comentarios que hubiera sobre este tema.

> En principio solo me falta lo del forms @emartinm .

Espero que sea un cambio pequeño y creo que va a hacer más claro el código.

2021-03-08 15:18 UTC, iburgoa13 commented
Ya lo he cambiado, espero que esté ya todo correcto de verdad :+1:

2021-03-08 17:48 UTC, emartinm commented on lsql/judge/forms.py
> +    start = forms.CharField(label='Desde', max_length=10)
La idea de tener un formulario para validación es que centralice toda la validación, no solo las longitudes. 
- start y end deben ser campos https://docs.djangoproject.com/en/3.1/ref/forms/fields/#datefield y así validas que te pasan fechas válidas. No necesitas parse_datetime que lance excepciones y capturarlas tú a mano
- Con https://docs.djangoproject.com/en/3.1/ref/forms/api/#django.forms.Form.clean realiza la comprobación personalizada de que start <= end
- Con https://docs.djangoproject.com/en/3.1/ref/validators/#maxvaluevalidator revisas que end es como máximo el día actual.

2021-03-08 17:50 UTC, emartinm commented on lsql/judge/views.py
> +def check_dates(request, end, up_to_classification_date, from_classification_date,
De esto se encargaría el formulario, y si no es válido te devolverá los errores que haya encontrado. Los mensajes concretos los personalizas en el validador y luego los usas para generar la página informativa.

2021-03-08 17:52 UTC, emartinm commented on lsql/judge/views.py
> +            parse_datetime(start)
Esto debería estar capturado en el formulario de manera automática al elegir el campo adecuado

2021-03-08 19:03 UTC, iburgoa13 commented
Hice commit ahora, prometo Enrique que estoy haciendo todo lo que puedo para cambiar lo mínimo e indispensable.. con todo eso tendría que cambiar muchas cosas y estoy tocando ya demasiado y cambiando test y cosas porque no salen como deben...
Lo de la fecha máxima, el input tiene su propio mensaje y ahí le inserto la fecha, eso no falla aunque lo metas por url.
La comparación de fechas la hago igualmente, lo he intentado por como me has dicho y llevo literal 1 hora viendo bien esos detalles e imposible. Espero que todo esto que hice valga.

2021-03-09 13:08 UTC, emartinm commented on lsql/judge/views.py
> +        if request.user.is_staff and result_form.is_valid() and result_form.clean():
Creo que no es necesario invocar a .clean() manualmente, debería hacerse automáticametne en is_valid()

2021-03-09 13:08 UTC, emartinm commented on lsql/judge/views.py
> +            result_form.clean()
Tampoco entiendo por qué hay que repetirlo

2021-03-09 14:11 UTC, emartinm commented
Estoy mirando cómo reorganizar show_result para reducir la complejidad, porque es verdad que tal y como está es difícil incorporar cosas. La idea que yo tenía (dime si es correcto) y el orden es el siguiente:

1. Validar las entradas. Si no son válidas devolver el mensaje de error (obtenido del formulario). Para evitar casuística posiblemente sea mejor no detectar si un usuario normal usa start y end, simplemente ignorarlo.
2. A partir de los parámetros, obtener el listado de submissions que generan el ranking.
3. A partir del listado de submissions y los parámetros, construir el ranking.
4. A partir del ranking, renderizar la plantilla.

Seguramente me estoy dejando comprobaciones y detalles relevantes, y ahí es donde necesito que me ayudes @iburgoa13 porque tú los tienes todos en la cabeza. Me gustaría ayudarte, porque la inclusión de fechas no es una tarea conceptualmente compleja pero si mover de lugar las validaciones es difícil es porque la organización de funciones no está ayudando o hay que generalizar algunas partes.

Reorganizar el código, siempre y cuando no cambiemos parámetros de la petición, no invalidaría ningún test.

2021-03-09 14:44 UTC, iburgoa13 commented
Según lo que dices así es.

2021-03-09 16:40 UTC, emartinm commented on lsql/judge/forms.py
> +                raise ValueError("Validacion fechas")
La intención detrás de mis mensajes es usar al máximo las facilidades de Django para validar entradas del usuario, porque eso hace el código más simple, mantenible y homogéneo. Tu commit incorpora muchas de las cosas que hemos comentado pero aún faltarían 3 detalles para explotar adecuadamente las facilidades de Django:

1. Una idea importante de la validación con formularios es usar excepciones ValidationError (ver por ejemplo https://docs.djangoproject.com/en/3.1/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other para un clean(self)). Estas excepciones se capturan automáticamente en el is_valid y se integran en el atributo form.errors (https://docs.djangoproject.com/en/3.1/ref/forms/api/#django.forms.Form.errors) que tendrá todos los errores encontrados.

2. Si form.is_valid() es falso, directamente generar una página con la plantilla que hiciste mostrando los mensajes de error sacados directamente de form.errors. Eso hace innecesaria la función error_value(err) porque ya no habría excepciones generadas por la validación de entradas y todo se manejaría en exactamente el mismo punto (además de simplificar el flujo de la ejecución). Realmente mi insistencia va dirigida a ese punto: que todo lo que tenga que ver con validación se trate en el formulario y con los mecanismos que proporciona Django.

3. Ahora mismo ResultForm no es aprovechado del todo porque debería poder detectar grupos válidos que serán números naturales (no confundir con grupos que sean números pero no existan, que es otra comprobación diferente de validación). Pero según veo es algo que sigue acabando en error_value, cuando se podría incorporar en ResultForm (ahora mismo es un CharField).

Por favor, dime si hay alguna distinción de casos compleja que impide centralizar toda la validación en ResultForm y generar los mensajes de error a partir de form.errors. Ten en cuenta que se pueden configurar algunos parámetros como opcionales.

2021-03-09 17:39 UTC, iburgoa13 commented
Vale, Enrique, por partes.
1 - He eliminado el try catch ya que no se usa ahora.
2 - La función del catch la he quitado de views.
3 - TODO se valida en el forms.
Creo que está ya todo lo pedido y espero que así sea, no sé que más tocar ya y qué más hacer, creo que está mucho más completo ahora y espero que lo suficiente para el último merge.

2021-03-09 17:39 UTC, iburgoa13 commented
Si es falso el valid llama a notfound ya que interpreto yo, que es mejor que llame a eso, ya que la página en sí, no existe o los parámetros son inválidos.

2021-03-09 17:40 UTC, iburgoa13 commented
El error devuelve diccionario y no sé usarlo, es mejor usar non_field_errors, directamente devuelve el valor de ValidationError.
Espero que todo OK.

2021-03-09 20:08 UTC, emartinm commented on lsql/judge/forms.py
> +                raise ValueError("Validacion fechas")
El punto 3 de mi contestación no tiene sentido, has hecho bien en ignorarlo. Estaba confundiendo grupo, que sí que usamos nombres, con colección, que se identifican con su clave primaria. Perdona la confusión.

2021-03-09 20:24 UTC, emartinm commented
Ahora toda la validación se hace en el formulario y la generación de errores por fallos de validación se hace en un único punto. Creo que la complejidad global de esta vista ha bajado un poco y ahora es más fácil de seguir.

`forms.errors` es un diccionario con todos los errores que ha encontrado la validación: la clave el es campo y el valor una lista con los mensajes de error. Los errores que no pertenecen a ningún campo (como la comprobación manual de start<= end) se almacenan en una clave all. `non_field_errors` devuelve esos errores sin campo, y creo que no contendrán errores que sí están asociados a un campo. Es un detalle menor, **el PR está muy bien y voy a aceptarlo ahora mismo**. Pero sí que te quería pedir permiso, una vez el PR está aceptado, para tratar de probar form.errors a ver si consigo sacar la página de error directamente de forms.errors.

Pero sobre todo, **¡enhorabuena y gracias por el trabajo!**

2021-03-09 20:25 UTC, merged