Descargar ranking
emartinm/lsql pull request #48
Opened 2021-03-22 13:10 UTC by Tamiflu9

2021-03-23 12:30 UTC, emartinm requested changes
Un PR muy completo, te dejo algunos comentarios menores

2021-03-23 12:30 UTC, emartinm commented on lsql/judge/tests/test_ranking.py
> +        client.login(username=user.username, password='2222')
¿Para qué haces login y logout (en línea 34) para añadir elementos a la BD? El login es necesario para hacer client.get o client.post

2021-03-23 12:30 UTC, emartinm commented on lsql/judge/tests/test_ranking.py
> +        # Teacher download ranking
Los comentarios están muy bien. Como cada uno inicia una "parte" del test, te pediría que pongas una línea en blanco para separar visualmente estas partes

2021-03-23 12:30 UTC, emartinm commented on lsql/judge/tests/test_ranking.py
> +        file = tempfile.NamedTemporaryFile(mode='w+b', buffering=-1, suffix='.xlsx')
No sirve igual un TemporaryFile? Lo digo porque no pareces usar el nombre

2021-03-23 12:45 UTC, Tamiflu9 commented on lsql/judge/templates/results.html
> +            <button type="button" class="btn btn-primary" title="csv con el ranking">Ranking</button>
Vale si , que queda mas claro así

2021-03-23 12:48 UTC, Tamiflu9 commented on requirements.txt
> +colorama==0.4.4
Es que si la desinstalo me saltan estos errores:
![colorama](https://user-images.githubusercontent.com/33600064/112148658-6b0dd000-8bde-11eb-8088-d87d60b4e8a5.png)

2021-03-23 15:08 UTC, emartinm commented on requirements.txt
> +colorama==0.4.4
Acabo de ver que logzero en Windows necesita colorama, por eso nunca he tenido que instalar ese paquete ni se me ha instalado automáticamente en Linux. ¿Puedes ejecutar `pip show colorama` y `pip show logzero` y confirmar qué es lo que te aparece? Para comprobar que detecta bien los requisitos.

2021-03-23 17:12 UTC, Tamiflu9 commented on requirements.txt
> +colorama==0.4.4
Esto es lo que me aparece:
![colorama](https://user-images.githubusercontent.com/33600064/112188412-42e49800-8c03-11eb-8028-1d55e1084182.png)

2021-03-23 17:13 UTC, Tamiflu9 commented on lsql/judge/views.py
> +    html = show_result(request, collection_id).content.decode('utf-8')
Vale, esto ya esta cambiado.

2021-03-23 17:15 UTC, Tamiflu9 commented on lsql/judge/views.py
> +def download_ranking(request, collection_id):
Vale, he añadido algún comentario antes de cada `for` para ver que datos son los que esta cogiendo. Las líneas en blanco en un principio las borre porque el pylint se quejaba de algunos espacios en blanco.

2021-03-23 17:19 UTC, emartinm commented on requirements.txt
> +colorama==0.4.4
Vale, pues entonces se confirma que lo necesita tanto logzero como pylint en Windows. Como el `requirements.txt` está pensado más para el despliegue, elimína `colorama` del fichero para que no se instale sin necesidad en el servidor. Sobre todo sabiendo que cuando vosotros carguéis los paquetes en Windows se bajará automáticamente porque es una dependencia y no os dará problemas que no esté en `requirements.txt`

2021-03-23 17:19 UTC, emartinm commented on lsql/judge/views.py
> +def download_ranking(request, collection_id):
Quizá se queje si dejas más de una línea en blanco, pero con una sola no lo hace

2021-03-23 17:24 UTC, Tamiflu9 commented on lsql/judge/tests/test_ranking.py
> +        file = tempfile.NamedTemporaryFile(mode='w+b', buffering=-1, suffix='.xlsx')
Uso el `NamedTemporaryFile` porque para poder usar la función `load_workbook` necesitaba que fuera un archivo `.xlsx` y el único que me reconocía el `suffix='.xlsx`' era ese. 
Si usaba el `TemporaryFile `me daba erorres:
![tmp](https://user-images.githubusercontent.com/33600064/112189788-a91dea80-8c04-11eb-9cdc-a7a3c3371ca8.png)

2021-03-23 17:24 UTC, Tamiflu9 commented on lsql/judge/tests/test_ranking.py
> +        # Teacher download ranking
vale, cambiado

2021-03-23 17:28 UTC, Tamiflu9 commented on lsql/judge/tests/test_ranking.py
> +        client.login(username=user.username, password='2222')
Ah pues si es tontería, no me había dado cuenta.

2021-03-23 17:31 UTC, Tamiflu9 commented on requirements.txt
> +colorama==0.4.4
Vale perfecto, entonces lo borro.

2021-03-23 17:33 UTC, Tamiflu9 commented on lsql/judge/views.py
> +def download_ranking(request, collection_id):
Ah vale pues igual deje dos líneas en vez de una.

2021-03-23 17:39 UTC, Tamiflu9 commented on lsql/judge/views.py
> +            for j in exercises:
Vale, esto ya cambiado también

2021-03-24 19:24 UTC, Tamiflu9 commented
Ahora no entiendo muy bien el que falla, si me sale todo al 100%
![tfg](https://user-images.githubusercontent.com/33600064/112371348-ccb56380-8cde-11eb-809d-423787737046.png)

2021-03-25 09:43 UTC, emartinm commented
> Ahora no entiendo muy bien el que falla, si me sale todo al 100%
> ![tfg](https://user-images.githubusercontent.com/33600064/112371348-ccb56380-8cde-11eb-809d-423787737046.png)

En estos casos vete a la entrada que aparece "Travis CI - Pull Request" que hay justo arriba para ver qué está fallando. Es este caso parece haber dos bloques de líneas que no se llegan a ejecutar: https://travis-ci.com/github/emartinm/lsql/builds/221105484

2021-03-25 09:48 UTC, emartinm commented
De hecho, por alguna razón TravisCI recibe un error `IndexError` en `test_download_ranking (judge.tests.test_ranking.RankingTest)` en un `file = path[6]`. Puede ser alguna diferencia Linux/Windows respecto a los ficheros, pero seguro que hay alguna manera de hacer el código para que sea interoperable.

2021-03-25 09:51 UTC, emartinm commented on lsql/judge/views.py
> +        path = temp.name.split("\\")
Esto es lo que te da problemas: el separador `\` es único de Windows. Pero creo que estás usando mal los temporales. La gracia es que se generen automáticamente en el directorio de temporales, que no tienes ni por qué conocer. ¿Por qué troceas esa ruta y te quedas con el 7 bloque? ¿Por qué no usas la ruta completa?

2021-03-25 09:52 UTC, emartinm commented on lsql/judge/views.py
> +def download_ranking(request, collection_id):
Ahora se le mucho más cómodo, ¡gracias!

2021-03-25 09:55 UTC, emartinm commented on lsql/judge/views.py
> +        os.remove(file)
Revisa la documentación https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile. Este tipo de ficheros se borra en cuanto se cierra.

2021-03-25 11:07 UTC, Tamiflu9 commented on lsql/judge/views.py
> +        os.remove(file)
Ay si es verdad, no hace falta borrarlo.

2021-03-25 11:09 UTC, Tamiflu9 commented on lsql/judge/views.py
> +        path = temp.name.split("\\")
Es que para hacer el `workbook.save()` necesito pasarle el nombre del archivo, si le paso la ruta no lo reconoce y no guarda anda en el archivo y al descargarlo esta vacio.

Por eso use el `mkstemp()` que aprecia que no daba problemas con eso.

2021-03-25 11:35 UTC, emartinm commented on lsql/judge/views.py
> +        path = temp.name.split("\\")
¿Pero no es exactamente lo que hace en este ejemplo de la documentación de `openpyxl`?
https://openpyxl.readthedocs.io/en/stable/tutorial.html#saving-as-a-stream

2021-03-25 11:56 UTC, Tamiflu9 commented on lsql/judge/views.py
> +        path = temp.name.split("\\")
Haciéndolo así me pone que no tengo permiso:
`PermissionError: [Errno 13] Permission denied: 'C:\\Users\\tamara\\AppData\\Local\\Temp\\tmpycr3196y'` 

![per](https://user-images.githubusercontent.com/33600064/112469075-51e55a80-8d69-11eb-8676-f92de75fb0a5.png)

2021-03-25 12:24 UTC, emartinm commented on lsql/judge/views.py
> +        path = temp.name.split("\\")
¿Y por qué no tienes permisos sobre ese fichero que se acaba de crear? Estos comportamientos de Windows se escapan completamente a mi conocimiento. Si te da la lata trata de usar https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp y haz un manejo más manual (pero usando el fichero que crea, no el prefijo). Ese método devuelve una pareja (fichero abierto, ruta completa). ¿Quizá haya que cerrar el fichero antes de salvar el workbook?

2021-03-27 13:39 UTC, emartinm commented on lsql/judge/views.py
> +        os.remove(file)
Veo que lo sigues borrando con `os.remove(name)`, supongo que mejor prevenir que curar

2021-03-27 13:41 UTC, merged