BD iniciales
emartinm/lsql pull request #52
Opened 2021-03-25 21:43 UTC by ivarui01

Añadida funcionalidad de permitir varias BD iniciales en los problemas select

2021-03-26 09:55 UTC, emartinm commented
Añade algunas capturas de pantalla para ilustrar el funcionamiento de esta mejora

2021-03-26 10:18 UTC, emartinm requested changes
Tengo muy pocos comentarios, la verdad es que este PR me parece muy conciso y muy claro. Lo único, incluye capturas de pantalla donde se vean los mensajes de retroalimentación en los distintos casos (fallo en la 1ª BD, fallo en las demás BD) y también cómo se muestra un problema para comprobar que se siguen mostrando igual

2021-03-26 10:18 UTC, emartinm commented on lsql/judge/models.py
> +            res = executor.execute_select_test(self.create_sql, self.first_insert_sql(), self.solution, output_db=True)
no hay nada diferente entre el primer caso y el resto, no? Lo digo para inicializar ambos campos a `[]` y procesar todo `insert_sql_list` de golpe dentro del bucle. Así parece que hay que hacer cosas distintas, que no es el caso.

2021-03-26 10:18 UTC, emartinm commented on lsql/judge/models.py
> +            self.expected_result = [res['post']]
En estos tipos de problemas en los que se ignora que haya varias BD y siempre se usa la primera, pon un comentario arriba del todo donde se explique, porque es importante dejarlo documentado para el futuro:

    # IMPORTANT: blablabla

2021-03-26 10:18 UTC, emartinm commented on lsql/judge/models.py
> +    def first_insert_sql(self):
Si las quieres dejar tampoco me parece terrible, pero al menos simplifica `extra_insert_sql`

2021-03-26 14:27 UTC, ivarui01 commented
Los problemas se siguen mostrando de la misma manera que antes:
![image](https://user-images.githubusercontent.com/61693814/112645864-351f5480-8e47-11eb-8ffd-737c5e402f2c.png)
Retroalimentación cuando falla en la primera BD:
![image](https://user-images.githubusercontent.com/61693814/112646020-626c0280-8e47-11eb-8ecf-19f468dbc434.png)
Retroalimentación cuando el resultado es correcto para la primera BD pero no para otra de las secundarias:
![image](https://user-images.githubusercontent.com/61693814/112646246-93e4ce00-8e47-11eb-94bb-bc65dd51b704.png)
![image](https://user-images.githubusercontent.com/61693814/112646457-c989b700-8e47-11eb-9a0d-90e9839e1cd9.png)

2021-03-27 11:40 UTC, emartinm commented
¿Has terminado la corrección? Si es así, ponme un comentario "Corregido" en cada comentario para que sepa los que puedo ir revisando y cerrando.

2021-03-27 12:03 UTC, ivarui01 commented on lsql/judge/models.py
> +    __insert_separation = "-- @new data base@"
Corregido

2021-03-27 12:03 UTC, ivarui01 commented on lsql/judge/models.py
> +    def first_insert_sql(self):
Corregido

2021-03-27 12:04 UTC, ivarui01 commented on lsql/judge/models.py
> +            res = executor.execute_select_test(self.create_sql, self.first_insert_sql(), self.solution, output_db=True)
Corregido

2021-03-27 12:04 UTC, ivarui01 commented on lsql/judge/models.py
> +            self.expected_result = [res['post']]
Corregido

2021-03-27 13:32 UTC, emartinm commented
Perfecto, ¡muchas gracias!

2021-03-27 13:33 UTC, merged