Encabezado vista logros de usuario
emartinm/lsql pull request #56
Opened 2021-03-29 14:25 UTC by Dashito14

![image](https://user-images.githubusercontent.com/48255774/112851526-5aac9800-90ab-11eb-87e6-57c1a7eadff8.png)

Está en un .CSS aparte lo de cambiar el formato del nombre. También se puede cambiar de color y lo que sea fácilmente.

2021-03-29 15:58 UTC, emartinm requested changes

2021-03-29 15:58 UTC, emartinm commented on lsql/judge/templates/achievements.html
> +<h1>Página de logros de <a class="headAchievement">{{ name }}</a></h1>
Si no es un enlace no uses la etiqueta `<a>`. Para agrupar elementos únicamente para asignarles estilo usa `<span>`

2021-03-29 15:58 UTC, emartinm commented on lsql/judge/views.py
> +                                                 'name': this_user.username})
mejor `username` que proporciona más información

2021-03-30 07:07 UTC, Dashito14 commented
He tenido que hacer dos `commit` porque ayer estuvimos haciendo pruebas en mi repositorio también y se me había olvidado eliminar unas líneas.

2021-03-30 07:08 UTC, Dashito14 commented on lsql/judge/views.py
> +                                                 'name': this_user.username})
Corregido

2021-03-30 07:08 UTC, Dashito14 commented on lsql/judge/templates/achievements.html
> +<h1>Página de logros de <a class="headAchievement">{{ name }}</a></h1>
Corregido

2021-03-30 09:42 UTC, emartinm commented
Perfecto, muchas gracias!!

2021-03-30 09:43 UTC, merged