Discriminant problem
emartinm/lsql pull request #63
Opened 2021-04-11 15:51 UTC by Dashito14

![image](https://user-images.githubusercontent.com/48255774/114310729-10380c00-9aec-11eb-8fc9-210d51052961.png)

**_________________________________________________________________________________________________________________________________________**
**_________________________________________________________________________________________________________________________________________**

![image](https://user-images.githubusercontent.com/48255774/114311243-38c10580-9aee-11eb-9077-9abaf690d62e.png)

**_________________________________________________________________________________________________________________________________________**
**_________________________________________________________________________________________________________________________________________**

![image](https://user-images.githubusercontent.com/48255774/114311263-51312000-9aee-11eb-9280-a9b148c66a58.png)

**_________________________________________________________________________________________________________________________________________**
**_________________________________________________________________________________________________________________________________________**

![image](https://user-images.githubusercontent.com/48255774/114311306-8473af00-9aee-11eb-987e-ccf30fe6be24.png)

**_________________________________________________________________________________________________________________________________________**
**_________________________________________________________________________________________________________________________________________**

![image](https://user-images.githubusercontent.com/48255774/114311310-8a699000-9aee-11eb-8519-75bb351116fc.png)

**_________________________________________________________________________________________________________________________________________**
**_________________________________________________________________________________________________________________________________________**

![image](https://user-images.githubusercontent.com/48255774/114311317-8fc6da80-9aee-11eb-8001-a7dcadf29e50.png)

2021-04-11 19:10 UTC, emartinm requested changes
Pongo algunas preguntas y sugerencias menores, pero en global me ha gustado mucho el PR.

2021-04-11 19:10 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Por completitud, añade tests para comprobar el WA y AC en un problema discriminante **que no tiene en cuenta el orden**. Ahora mismo el problema sin orden solo se usa para ver que la página HTML generada contiene la consulta errónea.

2021-04-11 19:10 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +def create_discriminant_problem(important_order, collection, name='Ejemplo'):
Si esta función no se usa aquí sino únicamente en test_submit, yo la movería a ese módulo.

2021-04-11 19:10 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
También haría un par de pruebas para ver que con y sin orden, enviar INSERTs que dan fallos al ser ejecutadas muestra devuelve la respuesta adecuada (Veredict.RE, supongo)

2021-04-11 19:10 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        with self.assertRaises(Exception):
Trata de ser más específico, qué excepción concreta debe lanzar el clean()?

2021-04-11 19:10 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        with self.assertRaises(Exception):
En este caso cuál es el error? No lo veo :-s

2021-04-12 06:44 UTC, Dashito14 commented on lsql/judge/feedback.py
> +    :return: (str) HTML code with the feedback, or '' if the table rows are equal (considering order)
Efectivamente. Corregido.

2021-04-12 06:46 UTC, Dashito14 commented on lsql/judge/models.py
> +    """Problem that requires an INSERT as solution"""
![image](https://user-images.githubusercontent.com/48255774/114351921-8596f180-9b6b-11eb-8040-9b01504c3bf7.png)

¿Así o más? Es por no alargar mucho el comentario en la función.

2021-04-12 06:47 UTC, Dashito14 commented on lsql/judge/models.py
> +    def judge(self, code, executor):
Sí, de hecho en ningún problema tiene comentario `judge` ni `problem_type`, creo que es porque ya está comentado en `Problem`. ¿Quieres que ponga un comentario igualmente?

2021-04-12 06:50 UTC, Dashito14 commented on lsql/judge/models.py
> +        if veredict != VeredictCode.AC:
Toda la razón. Corregido.

`return compare_discriminant_db(i_query['result'], c_query['result'], self.check_order)`

2021-04-12 06:53 UTC, Dashito14 commented on lsql/judge/tests/test_views.py
> +        with self.assertRaises(Exception):
`insert = "INSERT INTO test_table_1 VALUES (1997, 1997);\
                INSERT INTO test_table_2  VALUES (1994, 1994);"`

El error está en hacer un INSERT en una tabla que no existe: `test_table_2`
¿Qué error lanzaría esto exactamente? Es que en el clean() puse Exception.

2021-04-12 06:55 UTC, Dashito14 commented on lsql/judge/tests/test_views.py
> +def create_discriminant_problem(important_order, collection, name='Ejemplo'):
Sí. Al hacer ayer todo el cambio de ficheros no me di cuenta. Corregido.

2021-04-12 07:22 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
No se como provocar **Veredict.RE**. He probado con los siguientes INSERT:

`'INSERT INTO test_table_1 VALUES (2021); INSERT INTO test_table_1 VALUES (2021)'`
`'INSERT test_table_1 VALUES (2021);'`
`'INSERT INTO test_table_1 VALUES (a);'`
`'INSERT INTO test_table VALUES (2021);'      `  

Solo me han dado **WA** y **IE**.

2021-04-12 07:27 UTC, Dashito14 commented on lsql/judge/models.py
> +        i_query = executor.execute_select_test(self.create_sql, self.insert_sql + code,
Espero al comentario de @jcorreas 
¿En un principio sería poner `self.insert_sql_list()` con los dos INSERT distintos que hay no? El del `correct_query` y el de `incorrect_query`

2021-04-12 08:40 UTC, jcorreas commented on lsql/judge/models.py
> +        i_query = executor.execute_select_test(self.create_sql, self.insert_sql + code,
Efectivamente, no tiene mucho sentido tener varias BD, porque la modificación de la BD que propone el alumno puede no ser aplicable a otras BD que el alumno no tiene disponibles (por ejemplo, pueden producirse errores de clave duplicada, FK inexistente, etc).  

De hecho, poniéndome la gorra de profesor malicioso, lo que sí tendría sentido sería tener *varias consultas incorrectas* y que el alumno solo vea una. Cuando se propone una corrección a la BD, que se prueben esas otras consultas y se indique al alumno que aun así el caso de prueba (la BD inicial + los INSERT que propone) aún no permiten generar un buen conjunto de casos de prueba. 

En cualquier caso, esto es solo un pensamiento en voz alta: creo que esto *no lo debemos implementar*, aunque es buena idea planteárnoslo, y es un buen apunte para documentar esta tarea (no hay que implementar todo lo que se nos ocurre, pero sí podría comentarse en la memoria). Es realmente complicado hacer una buena BD de prueba para una consulta, a mí me parece que este tipo de ejercicios ayudarán mucho a comprender cómo probar una consulta. Y además está el trabajo por parte del profesor para añadir tantas consultas incorrectas :-).

2021-04-12 09:48 UTC, Dashito14 commented on lsql/judge/models.py
> +        i_query = executor.execute_select_test(self.create_sql, self.insert_sql + code,
Entonces, ¿qué debo hacer?

2021-04-12 10:24 UTC, emartinm commented on lsql/judge/models.py
> +    """Problem that requires an INSERT as solution"""
Sí, me parece más informativo así.

2021-04-12 10:25 UTC, emartinm commented on lsql/judge/models.py
> +    def judge(self, code, executor):
No, era solo una duda personal. Tiene sentido que al ser un método heredado "herede" también el comentario :-)

2021-04-12 10:29 UTC, emartinm commented on lsql/judge/models.py
> +        i_query = executor.execute_select_test(self.create_sql, self.insert_sql + code,
**Desde el punto de vista del código**, por uniformidad, quizá sea más claro que uses `self.insert_sql_list()` teniendo en cuenta que será una lista unitaria, es decir, siempre usarás el elemento `[0]`. Pero cada vez que lo uses añade un comentario en esa línea incidiendo en que este tipo de problema tiene una única BD inicial. 

**Desde el punto de vista de la memoria**, la reflexión de Jesús me parece muy acertada y te recomendaría apuntarla para mencionarlo en la memoria cuando hables de este tipo de problema nuevo.

2021-04-12 10:37 UTC, Dashito14 commented on lsql/judge/models.py
> +    """Problem that requires an INSERT as solution"""
Corregido.

2021-04-12 10:40 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
¡Error interno no mola nada! ¿En qué caso te ha dado eso? Eso es algo que habría que manejar, porque IE significa "algo ha fallado y no sé exactamente qué". Me interesaría mucho conocer ese caso porque a lo mejor hay algo que no estamos manejando bien.

Para un RE puedes probar con un INSERT **sintácticamente inválido** como este, al que le falta un INTO mínimo:

    INSERT merienda;

Algo relacionado con los VE: ¿por defecto un problema de este tipo acepta exactamente 1 sentencia SQL? Quizá en este caso sería interesante cambiar el límite por defecto a entre 1 y 50. Sí, me he inventado el 50 :-) Pero me imagino que en general no querremos constreñir mucho a los estudiantes para que sean capaces de encontrar exactamente una fila que da al traste con la consulta. O quizá sí? Pido el comodín de @jcorreas

2021-04-12 10:42 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        with self.assertRaises(Exception):
Dado que en el `clean` haces validación de los datos del problema, si están mal me parece que lo mejor es lanzar una `ValidationError` como hacen los demás `clean` de otros problemas.

2021-04-12 10:43 UTC, emartinm commented on lsql/judge/tests/test_views.py
> +        with self.assertRaises(Exception):
Notarás que todo el código de otros `clean` está dentro de un `try`, así que cualquier cosa que falle durante la limpieza se emite como error de validación.

2021-04-12 10:46 UTC, emartinm commented
Por cierto, no te lo dije en el comentario general de ayer pero te agradezco mucho todas las erratas que vas detectando y corrigiendo en el código aunque no formen parte de tu PR. **¡¡Gracias!!**

2021-04-12 10:51 UTC, jcorreas commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
No, no debe limitarse a exactamente un INSERT. De hecho, puede ocurrir que sea imprescindible añadir filas en varias tablas (por ejemplo para sentencias de tipo GROUP BY con funciones de agregación que ordenen por dichas funciones; o para sentencias complejas con varios joins o consultas anidadas, etc.). 

Al diseñar el problema también nos limitaría mucho el tipo de preguntas, porque siempre tenemos que dar una BD inicial a la que le falte una sola fila...

2021-04-12 10:52 UTC, jcorreas commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Estoy suponiendo que solo se van a permitir INSERT, aunque también se podrían considerar otras sentencias DML (UPDATE y DELETE), pero en cualquier caso se deben permitir varias.

2021-04-12 11:03 UTC, Dashito14 commented on lsql/judge/models.py
> +        i_query = executor.execute_select_test(self.create_sql, self.insert_sql + code,
Corregido

2021-04-12 11:06 UTC, Dashito14 commented on lsql/judge/tests/test_views.py
> +        with self.assertRaises(Exception):
Quité el try para incluirlo en el siguiente PR con los ZIP. Lo añado y le meto el ValidationError.

2021-04-12 11:18 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Al tener el por defecto en `Problem` como 1 lo he dejado así. Lo puedo cambiar. De todas formas en este caso me ha dado **WA**.

He puesto lo que me ha dado cada uno de los `INSERT` en el comentario anterior. Creo que debo haber hecho algo mal porque me dan muchos **IE**.

2021-04-12 16:41 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Es que tienes que añadir algo de manejo en la función `judge`. Si `execute_select_test` falla en alguno de los pasos lanza una excepción `ExecutorException` con datos de lo que ha fallado, concretamente un valor como `OracleStatusCode.EXECUTE_INSERT` que te dice en qué paso falló. En este caso, si el error es achacable a los INSERT el error es del usuario, así que habría que capturar y relanzar esa excepción con valor `OracleStatusCode.EXECUTE_USER_CODE` para que la vista `judge:submit` genere un RE. ¿Esto cambiaría todos los IE por RE?

¿Con respecto al IndexError, eso es lo que lanza la función `judge` en ese caso? ¿Puedes pegarme la salida por pantalla para ver los detalles del error?

2021-04-12 16:47 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Para @jcorreas : sí, estos problemas soportan más de 1 sentencia INSERT, es configurable. Lo único es que *por defecto*, si no se pone nada, el valor mínimo y máximo vale 1 (pero se puede cambiar). Mi pregunta iba más en la dirección de si tiene sentido que para este tipo de problemas los valores por defecto si no se pone nada sean otros mayores, por ejemplo, min =1 max=50. 

Pero realmente no sé cómo se hace, ni si puede hacerse :-s Así que @Dashito14 ni te molestes en pensarlo :-)

2021-04-13 07:14 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
![image](https://user-images.githubusercontent.com/48255774/114511786-a5e0b200-9c38-11eb-816b-88b3a776248f.png)

2021-04-13 09:17 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Vale, este problema aparece en `line_col_from_offset` que trata de traducir un offset de error a una línea y columna para marcarlo en el cuadro de código, y este problema en principio se escaparía de tus competencias. ¿Puedes hacer un commit con el código actual, aunque no sea una revisión completa, para que yo pueda descargarme tu rama y poder depurarlo en mi máquina? A lo mejor la conclusión es que sí que es tu competencia, pero necesito mirarlo :-)

2021-04-13 09:23 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Voy, paso los test y pylint y lo subo.

2021-04-13 09:32 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Ok, he mirado y tengo una sospecha grande de que el problema está en que `execute_select_test` no consideraba que los INSERT pudieran fallar, únicamente el SELECT. Cuando actualices tu rama lo miro y trato de arreglarlo para que el test `test_discriminant_problem` deje de lanzar esa excepción `IndexError` inesperada. Entiendo que en el commit que subas todos los tests pasan salvo ese, tal y como veo en la captura de pantalla.

2021-04-13 09:33 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
No cambies código, que lo voy a mirar tu rama ahora y quizá te haga un pull con cambios en oracle_driver.py.

2021-04-13 09:34 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Bueno, realmente pasan todos, he puesto otro ejemplo que lance RE. Si quieres cuando lo revises incluyo un nuevo test que compruebe ese caso también. Al haber tantos tipos de errores con los INSERT pensaba que con que pusiera uno que lanzara RE ya valía.

2021-04-13 10:37 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
El problema estaba en `execute_select_test` porque cuando Oracle lanzaba una execpción se asumía que el error estaba en el código de SELECT porque estaba pensado para corregir ejercicios de tipo SELECT. Al usar `execute_select_test` para los problemas de discrimiar eso ya no es verdad, porque el error nunca estará en las consultas sino en los INSERT. Así que traducir el offset donde está el error (lo que da Oracle) a una (columna, fila) para reportarlo de manera informativa fallaba.

De la misma manera, si falla algún INSERT del usuario queremos darle la información de qué parte de su INSERT está generando el error, así que reutilizar `execute_select_test` tal cual no funcionaba para esto. Además, usar dos veces `execute_select_test` hace que todo vaya más lento porque hay que crear dos veces un usuario temporal, crear dos veces las tablas, insertar dos veces las mismas filas, destruir dos veces el usuario temporal... Asi que he creado un nuevo método `execute_discriminant_test` que le pasas los CREATE, INSERT del problema, INSERT del usuario, consulta correcta y consulta incorrecta y lo hace todo con el mismo usuario, redirigiendo los problemas al código del usuario para culpar al INSERT adecuado.

Acabo de subir cambios **a tu rama de tu repositorio para no liarte con mezclas** (https://github.com/Dashito14/lsql/commit/bc0ea48970bf94927f1d7ab02c9e23c7d9a10a37). Solo tienes que hacer `git pull` para recibir estos cambios. Lo he subido lo más rápido posible para no retrasarte, pero todavía tengo que hacer tests para garantizar la cobertura completa del nuevo método `execute_discriminant_test`. Así que integra los cambios y termina tu PR sin importar que `judge/oracle_driver.py` no tenga la cobertura completa (falta un par de líneas). Ya me encargo yo de conseguir el 100% en `judge/oracle_driver.py` y lo meto directamente en el repositorio principal (esta vez ya sí que lo hare en el repositorio principal).

2021-04-13 10:41 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
De acuerdo, voy con ello. Voy a releerme varias veces este comentario que tiene mucho comentario técnico. He entendido que tengo que cambiar el `judge` y utilizar la nueva función que me has dicho ¿no?

2021-04-13 10:45 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
No tienes que cambiar `judge`, ya lo adapté yo y pasa tus tests así que espero haberlo hecho bien. También he añadido esos dos casos en los que salía IndexError y ahora ya se manejan bien a RE. Pero echa un vistazo a los cambios de mi commit para estar seguro con lo que he tocado.

2021-04-13 10:54 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
![image](https://user-images.githubusercontent.com/48255774/114541669-4fcf3700-9c57-11eb-9f84-a1b93318d09a.png)

Sale este mensaje pero nada en el cuadro rojo, entiendo que eso lo tengo que añadir, ¿no?

2021-04-13 11:01 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Sí, sería importante que apareciera la retroalimentación además del veredicto. Es verdad que en los tests de unidad únicamente se comprueba el resultado del veredicto (AC, RE, etc.) y no la retroalimentación, pero me alegra que lo hayas comprobado a mano.

Echa un vistazo en la vista `submit` (linea 371 en adelante) para ver qué excepción le llega, si tienes los datos esperados y si está fallando alguna conexón.

2021-04-13 11:04 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Revisa esto y cuando subas el siguiente commit que lo arregle vuelvo a mirar el resto de comentarios. Es verdad que seguramente no falte nada más.

2021-04-13 11:18 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
![image](https://user-images.githubusercontent.com/48255774/114544154-89ee0800-9c5a-11eb-8bbe-d5dfd11cdba6.png)
![image](https://user-images.githubusercontent.com/48255774/114544166-8f4b5280-9c5a-11eb-8049-1b4c38e53a45.png)
![image](https://user-images.githubusercontent.com/48255774/114544186-93777000-9c5a-11eb-8aac-4f00d05d061b.png)

![image](https://user-images.githubusercontent.com/48255774/114544177-91151600-9c5a-11eb-8efd-cfd68170a35b.png)

Pues en un principio ya estaría. Te dejo algunos ejemplos. Paso **pylint** y los **test** por si acaso cambia algo y hago COMMIT.

2021-04-13 11:22 UTC, Dashito14 commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
He hecho el COMMIT.

2021-04-13 11:28 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        disc_problem = create_discriminant_problem(False, collection)
Perfecto, en cuanto termine TravisCI lo miro. ¿Me puedes pasar los datos del problema que has utilizado para los ejemplos de retroalimentación que has adjuntado? Lo digo para ponerlo en mi sistema local exactamente igual que lo tienes tú.

2021-04-13 11:40 UTC, emartinm approved these changes
Todos los cambios han sido aceptados. Gracias!

2021-04-13 11:46 UTC, merged