Segunda traducción y botón para cambiar idioma
emartinm/lsql pull request #74
Opened 2021-04-23 19:19 UTC by ivarui01

2021-04-24 08:56 UTC, emartinm commented on lsql/judge/templates/base.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css">
Solo por curiosidad:
- ¿al final las banderas se obtienen de la biblioteca `flag-icon`?
- ¿para qué sirve bootstrap-select?

2021-04-24 09:14 UTC, emartinm requested changes
Algunos comentarios muy menores en algunas traducciones, y alguna que otra pregunta de curiosidad. Pero cosa **muy** pequeña :smile:

2021-04-24 09:14 UTC, emartinm commented on lsql/judge/tests/test_languages.py
> +        self.assertIn(languages_to_flags.language_to_flag("en"), "flag-icon-us")
assertIn no es más bien un assertEqual?

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "name of the {number}ª column"
el ª para el inglés no funciona, debería ser 1st, 2nd, 3rd, y a partir de ahí **th** (4th, 5th...). Como no creo que se pueda manejar, mejor `th` para todos.

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +"The insert that you have provided does not allow detecting the erroneous "
insertion?

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "Data base"
Database?

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "User place"
No sé si es mejor *position*

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +"tried)"
tried -> attempt?

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "1º Student with more solved"
Como antes, el º no valdrá para inglés: 1st 2nd 3rd

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "SQL statement"
statement**s**?

2021-04-24 09:14 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "SQL statements"
Parece que está cruzada la traducción del plural/singular

2021-04-24 10:44 UTC, ivarui01 commented on lsql/judge/templates/base.html
> +    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/flag-icon-css/3.1.0/css/flag-icon.min.css">
No es de Bootstrap no, es que en la mayoría de webs aparece algo de Bootstrap y luego no tiene nada que ver, me equivoqué.
Lo de bootstrap-select lo quito para el siguiente commit, que lo metí para ver si podía poner el botón como los otros y al final se me olvido quitarlo.

2021-04-24 11:13 UTC, ivarui01 commented on lsql/judge/tests/test_languages.py
> +        self.assertIn(languages_to_flags.language_to_flag("en"), "flag-icon-us")
Corregido

2021-04-24 11:13 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "name of the {number}ª column"
Corregido.
Lo he cambiado aquí también:
![image](https://user-images.githubusercontent.com/61693814/115956750-e4128700-a4fe-11eb-93e0-9d333dfcacf5.png)

2021-04-24 11:13 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +"The insert that you have provided does not allow detecting the erroneous "
Corregido

2021-04-24 11:14 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "Data base"
Corregido

2021-04-24 11:14 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "User place"
Corregido

2021-04-24 11:14 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +"tried)"
Corregido

2021-04-24 11:14 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "1º Student with more solved"
Corregido

2021-04-24 11:14 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "SQL statement"
Corregido

2021-04-24 11:14 UTC, ivarui01 commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "SQL statements"
Corregido

2021-04-25 10:59 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "name of the {number}ª column"
Perfecto, sí. No es fácil darse cuenta de todas las traducciones :-s

2021-04-25 11:01 UTC, emartinm approved these changes
Perfecto!

2021-04-25 11:02 UTC, merged