Idioma en los problemas
emartinm/lsql pull request #76
Opened 2021-04-30 14:11 UTC by ivarui01

Se ha añadido un nuevo atributo a los problemas para indicar el idioma, también se muestran las banderas de los idiomas de los problemas de una colección en la lista de colecciones, menos cuando todos los problemas están en español.

2021-04-30 17:58 UTC, emartinm requested changes
3 comentarios muy menores

2021-04-30 17:58 UTC, emartinm commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
Trata de hacer la consulta ORM concreta que te devuelve directamente una lista de idiomas (creo que es `value_list` o algo así). No merece la pena hacer un bucle para esto.

2021-04-30 17:58 UTC, emartinm commented on lsql/judge/templates/collections.html
> +        <th scope="col"></th>
Creo que al final decidimos poner las banderas pegadas al nombre, separado con un espacio, no en una columna específica. ¿Están en una columna por alguna razón técnica?

2021-04-30 17:58 UTC, emartinm commented on lsql/judge/templatetags/languages_to_flags.py
> +    if (len(languages) == 1 and 'es' in languages):
Esto no es lo mismo que:

   if languages == ['es']:

2021-04-30 18:36 UTC, ivarui01 commented on lsql/judge/templates/collections.html
> +        <th scope="col"></th>
Lo puse al lado del nombre pero en otra columna, porque en la misma columna lo veo un poco feo, pero como quieras.
![image](https://user-images.githubusercontent.com/61693814/116738126-5a792280-a9f2-11eb-8487-6d25658956eb.png)

2021-04-30 19:25 UTC, ivarui01 commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
SI hago `Collection.problems(self).order_by('language').distinct('language').values_list('language', flat=True)` entonces `if languages == ['es']:` no funciona

2021-05-01 10:37 UTC, emartinm commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
¿Por qué no funciona? ¿Qué devuelve `Collection.problems(self).order_by('language').distinct('language').values_list('language', flat=True)`? Me refiero tanto al tipo como al valor.

2021-05-01 10:38 UTC, emartinm commented on lsql/judge/templates/collections.html
> +        <th scope="col"></th>
A mi gusta un poco más esta segunda opción de bandera al lado del nombre (algo completamente personal). @jcorreas , ¿tú qué opinas?

2021-05-01 10:50 UTC, emartinm commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
A todo esto, `problems` es un método de un objeto `Collection`, invócalo con `self.problems()` que queda mucho más claro.

2021-05-01 10:53 UTC, emartinm commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
> ¿Por qué no funciona? ¿Qué devuelve `Collection.problems(self).order_by('language').distinct('language').values_list('language', flat=True)`? Me refiero tanto al tipo como al valor.

Esto seguramente te devuelva un `QuerySet`, no una lista. Tendrás que pasarlo a lista si quieres comparar igualdad con otra lista.

2021-05-01 10:53 UTC, ivarui01 commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
Los valores los guarda bien, pero me devuelve un InheritanceQuerySet.

2021-05-01 10:54 UTC, emartinm commented on lsql/judge/templatetags/languages_to_flags.py
> +    if (len(languages) == 1 and 'es' in languages):
Mi comentario surge de que pensaba que `languages` era una lista. Si es un `QuerySet` no funcionará.

2021-05-01 10:55 UTC, ivarui01 commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
Vale, hay una función para pasarlo a una lista.

2021-05-01 10:59 UTC, emartinm commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
Entonces con un `list(...)` por fuera te lo pasa a lista.

2021-05-01 11:00 UTC, ivarui01 commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
Si si.

2021-05-01 14:14 UTC, ivarui01 commented on lsql/judge/models.py
> +        for problem in Collection.problems(self):
Corregido.

2021-05-01 14:14 UTC, ivarui01 commented on lsql/judge/templatetags/languages_to_flags.py
> +    if (len(languages) == 1 and 'es' in languages):
Corregido.

2021-05-01 15:45 UTC, emartinm commented on lsql/judge/templatetags/languages_to_flags.py
> +    print(languages)
Quitar print de depuración

2021-05-01 15:46 UTC, emartinm commented on lsql/judge/models.py
> +        return list(Collection.problems(self).order_by('language').distinct('language') \
self.problems().order_by...

2021-05-01 15:52 UTC, ivarui01 commented on lsql/judge/models.py
> +        return list(Collection.problems(self).order_by('language').distinct('language') \
Perdón se me había olvidado.

2021-05-01 15:57 UTC, ivarui01 commented on lsql/judge/templatetags/languages_to_flags.py
> +    print(languages)
Corregido.

2021-05-01 16:00 UTC, emartinm approved these changes
¡Perfecto! Cuando termine TravisCI lo integro del todo.

2021-05-01 16:02 UTC, merged