Traducción de logros y página de ayuda
emartinm/lsql pull request #77
Opened 2021-05-03 12:17 UTC by ivarui01

Se ha añadido la posibilidad de poner varios idiomas a los logros y el funcionamiento de la página de ayuda en varios idiomas.
![image](https://user-images.githubusercontent.com/61693814/116874735-15373980-ac1a-11eb-821e-8bad63835219.png)
![image](https://user-images.githubusercontent.com/61693814/116874772-23855580-ac1a-11eb-90af-fc9bfabb92ef.png)
![image](https://user-images.githubusercontent.com/61693814/116874852-46b00500-ac1a-11eb-8b79-dc7401b2b12e.png)
![image](https://user-images.githubusercontent.com/61693814/116874871-4e6fa980-ac1a-11eb-9fd7-24cf4d78acbe.png)

2021-05-03 12:38 UTC, ivarui01 commented
Se me había olvidado comprobar `coverage report -m`, aun así lo estoy viendo ahora y me pone que que no se comprueban muchas líneas de código en views.py que en principio no tienen mucho que ver con lo que he cambiado y no lo entiendo. Algunos parecen como espacios entre funciones.

2021-05-03 12:42 UTC, iburgoa13 commented
Buenas, me dio por mirar que yo de esto he vivido mucho.
El fallo Iván es que te falta hacer una comprobación en los test.
![image](https://user-images.githubusercontent.com/43571438/116877051-b4a9fb80-ac1d-11eb-9886-36973242a7a6.png)
Esta imagen es de views.py eso quiere decir que esa excepción no la tratas en test entonces te salta ese fallo.
Si añades el test se soluciona.

2021-05-03 12:47 UTC, ivarui01 commented
Esta aquí:
![image](https://user-images.githubusercontent.com/61693814/116877560-65b09600-ac1e-11eb-9f33-491ef776d48f.png)

2021-05-03 12:47 UTC, ivarui01 commented
![image](https://user-images.githubusercontent.com/61693814/116877623-7a8d2980-ac1e-11eb-9bc1-5e435a02d779.png)

2021-05-03 13:14 UTC, emartinm requested changes
No se obtiene la cobertura total, faltan 2 línea de `views.py`. Y me sorprende, porque sí que tienes tests pidiendo la página de ayuda en ruso...

```
Name                                       Stmts   Miss  Cover   Missing

------------------------------------------------------------------------

judge/admin.py                                78      0   100%

judge/apps.py                                  1      0   100%

judge/exceptions.py                           10      0   100%

judge/feedback.py                            141      0   100%

judge/forms.py                                29      0   100%

judge/models.py                              405      0   100%

judge/oracle_driver.py                       490      0   100%

judge/parse.py                               225      0   100%

judge/shell.py                                76      0   100%

judge/signals.py                              24      0   100%

judge/statistics.py                           25      0   100%

judge/templatetags/languages_to_flags.py      15      0   100%

judge/templatetags/random_tags.py             13      0   100%

judge/tests/test_feedback.py                 113      0   100%

judge/tests/test_languages.py                328      0   100%

judge/tests/test_models.py                   230      0   100%

judge/tests/test_oracle.py                   205      0   100%

judge/tests/test_parse.py                    131      0   100%

judge/tests/test_ranking.py                  251      0   100%

judge/tests/test_shell.py                     91      0   100%

judge/tests/test_statistics.py                55      0   100%

judge/tests/test_submit.py                   129      0   100%

judge/tests/test_tags.py                      16      0   100%

judge/tests/test_views.py                    533      0   100%

judge/types.py                                60      0   100%

judge/urls.py                                  6      0   100%

judge/views.py                               345      2    99%   141-142

------------------------------------------------------------------------

TOTAL                                       4025      2    99%
```

2021-05-03 13:18 UTC, ivarui01 commented
¿Y por que a mi me salen tantísimas líneas de código?

2021-05-03 13:28 UTC, emartinm commented
> ¿Y por que a mi me salen tantísimas líneas de código?

Cuando a mi me salen tantas líneas sin cubrir normalmente es porque algún test me falla debido a algún cambio y termina prematuramente, dejando varias cosas sin invocar. Independientemente de la cobertura, ¿te están pasando todos los tests con éxito?

2021-05-03 13:34 UTC, ivarui01 commented
Claro.
![image](https://user-images.githubusercontent.com/61693814/116882578-e5416380-ac24-11eb-85b1-739c646cf3ae.png)
Y veo que ahora me ha cambiado la cobertura.
![image](https://user-images.githubusercontent.com/61693814/116882661-fdb17e00-ac24-11eb-9c2f-9f835f7fac42.png)

2021-05-03 13:43 UTC, emartinm commented
El fichero tests.sh borra la información antigua de cobertura antes de lanzar los tests y generar el informe. Si ejecutas los comandos a mano y se te ha olvidado borrarlo quizá eso tenga que ver con que se vuelva loco y apunte a líneas vacías. Ahora al menos tienes el mismo mensaje que TravisCI, así que podrás depurar por qué razón no entra en esa rama.

2021-05-04 17:30 UTC, ivarui01 commented
Ya he visto cual es el problema, como el idioma ruso no esta disponible en la aplicación, cuando se cambia al ruso en los tests, como no existe, se pone el idioma por defecto que es el español. El test da correcto porque se muestra la página en español, pero no porque no exista la página de ayuda en ruso sino porque se carga el idioma español en vez del ruso. Entonces la manera de probar esto seria añadiendo un idioma que no tuviese página de ayuda, pero eso no lo podemos hacer.

2021-05-04 17:39 UTC, emartinm commented
Entonces elimina la página de ayuda en inglés para ejercitar esa rama. Si
alguna vez añadimos esa traducción perderemos cobertura, pero por ahora no
planeo que vayamos a hacerlo en un futuro cercano.

2021-05-05 08:58 UTC, emartinm approved these changes

2021-05-05 08:59 UTC, merged