cargar pistas con zip
emartinm/lsql pull request #85
Opened 2021-06-07 11:55 UTC by Tamiflu9

2021-06-07 15:34 UTC, emartinm commented
Perdona, @Tamiflu9 , que no he podido contestar a tus comentarios del issue hasta ahora y veo que ya has hecho el pull request. Voy a ignorar entonces esos comentarios y me centro en este PR.

2021-06-07 16:30 UTC, emartinm requested changes
Comentarios principales sobre el PR:

- Crear funciones para no repetir código de copiar-pegar.
- Eliminar todas la veces que has añadido `setattr(problem, 'hints_info', '')`.
- Revertir cambios en ficheros donde no hay que tocar nada, como test_oracle y similares.
- Algunas ideas para simplificar el código que extrae las pistas de una cadena.

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/signals.py
> +    for elem in kwargs['instance'].hints_info:
Si el código en los 6 tipos de problema es el mismo (y creo que lo debe ser), hay una función auxiliar que recorra las pistas y las salve a partir de la instancia y el sender

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/signals.py
> +    for elem in kwargs['instance'].hints_info:
La idea es hacer esto únicamente en los problemas que tienen definido ese atributo `hints_info` porque unos lo tendrán y otro no. La función para saber si existe un atributo es https://docs.python.org/3/library/functions.html#hasattr

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/signals.py
> +    for elem in kwargs['instance'].hints_info:
Por similitud con el código anterior de las señales, recibe el `sender` y emite un mensaje en el `log`

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        setattr(problem, 'hints_info', '')
Esto debería desaparecer porque ese parámetro solo debe existir en problemas cargados desde ZIP con fichero `hints.md`

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        hints = "3\r\n" \
Usa cadenas con 3 comillas para representar los saltos de línea, que queda mucho más legible:

    hints = """3
    Es **importante** consultar las tablas `Club` e `Inversiones`
    @@@new hint@@@
    5
    El resultado debe proyectar las siguientes filas:
     * Nombre renombrado a Name
     * Sede renombrado a Address"""

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +            setattr(problem, 'hints_info', hint_list)
Me estoy liando mucho con esto. Lo que debes comprobar es que al cargar el problema con los datos del ZIP, se cargan las pistas que están **en ese ZIP**. Aquí lees los datos del ZIP pero luego sobreescribes `hint_list` con lo que te ha salido de `hints`.

Y además del número de pistas deberías comprobar que el contenido es que aparecía en el ZIP.

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        with self.assertRaises(ZipFileParsingException):
Separa el test de casos buenos (las pistas se leen correctamente del ZIP) y estos dos donde se leen pistas que están mal formadas. 

En lugar de invocar directamente a `extract_hints_from_file` carga los problemas con pistas mal formadas desde su ZIP mal formado.

Además de mirar que se lanza una excepción `ZipFileParsingException` revisa que su mensaje es el que te esperas. Hay ejemplos de eso en otros tests del proyecto, es almacenar la excepción en un objeto `excp` como:

    self.assertRaises(ZipFileParsingException) as excp

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_languages.py
> +        setattr(problem, 'hints_info', '')
Elimina todos los setattr para asignar `''`

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_languages.py
> +        problem.clean()
Para esta tarea no debes tocar el código de otros módulos que no son sobre cargar pistas de un ZIP

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_models.py
> +        self.assertEqual(len(soup.find(id="bd").find_all('tbody')[0].find_all('tr')), 3)
Entiendo que aquí no ha cambiado nada salvo saltos de línea, no?

2021-06-07 16:30 UTC, emartinm commented on lsql/judge/tests/test_oracle.py
> +        problem_select = SelectProblem(title_md='Test Select', text_md='bla bla bla',
En este módulo no tendrías que tocar nada, pero parece que has cambiado `problem` por `problem_select`. Por simplicar el PR revierte estos cambios.

2021-06-07 17:59 UTC, Tamiflu9 commented on lsql/judge/models.py
> +                    setattr(problem, 'hints_info', '')
vale, solo debe estar en `parse.py` al leer los ficheros del zip, no?

2021-06-07 18:55 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +            if 'hints.md' in zfile.namelist():
entonces dejarlo como `extract_hints_from_file(zfile)` y hacer todo ahí y luego en vez de hacer en esa linea lo del
'`if 'hints.md' in zfile.namelist():`' poner  '`problem.hints_info = extract_hints_from_file(zfile)`' ?

2021-06-07 19:03 UTC, Tamiflu9 commented on lsql/judge/tests/test_models.py
> +        self.assertEqual(len(soup.find(id="bd").find_all('tbody')[0].find_all('tr')), 3)
si, es que el pylint se quejaba de que eran muy largas las filas

2021-06-07 19:04 UTC, Tamiflu9 commented on lsql/judge/tests/test_oracle.py
> +        problem_select = SelectProblem(title_md='Test Select', text_md='bla bla bla',
corregido

2021-06-07 19:05 UTC, Tamiflu9 commented on lsql/judge/tests/test_languages.py
> +        problem.clean()
corregido

2021-06-07 19:06 UTC, Tamiflu9 commented on lsql/judge/tests/test_languages.py
> +        setattr(problem, 'hints_info', '')
corregido

2021-06-07 19:08 UTC, Tamiflu9 commented on lsql/judge/shell.py
> +        setattr(prob, 'hints_info', '')
corregido

2021-06-07 19:11 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +            raise ZipFileParsingException('Invalid value for number of submissions in hints.md')
corregido

2021-06-07 19:11 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +            raise ZipFileParsingException('Invalid value for description in hints.md')
corregido

2021-06-07 19:11 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +        elem.remove(n_sub)
corregido

2021-06-07 19:11 UTC, Tamiflu9 commented on lsql/judge/signals.py
> +    for elem in kwargs['instance'].hints_info:
corregido

2021-06-07 19:11 UTC, Tamiflu9 commented on lsql/judge/signals.py
> +    for elem in kwargs['instance'].hints_info:
corregido

2021-06-07 19:12 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +        setattr(problem, 'hints_info', '')
corregido

2021-06-08 09:38 UTC, emartinm commented on lsql/judge/models.py
> +                    setattr(problem, 'hints_info', '')
Exacto, ese atributo dinámico solo debe existir en aquellos problemas cuyos datos se cargan de un ZIP. Si yo por ejemplo busco problema en la BD usando el ORM, lo modifico y lo salvo, en ningún momento tendrá ese parámetro. Y cuando llegase a la señal post_save detectaría que no existe y no haría nada (en tu caso detecta que el atributo es vacío, lo que obliga a modificar 57 ficheros no relacionados con el flujo parse->signal).

2021-06-08 09:42 UTC, emartinm commented on lsql/judge/parse.py
> +            if 'hints.md' in zfile.namelist():
Esa asignación siempre crearía un atributo `hints_info` en `problem` y te obligaría a decidir qué devolver cuando `zfile` no contiene pistas. Lo mejor es un `extract_hints_from_file(zfile, problem)` que no devuelve nada pero añade el campo `hints_info` en `problem` **únicamente si zfile tiene fichero de pistas**

2021-06-08 09:44 UTC, emartinm commented on lsql/judge/tests/test_models.py
> +        self.assertEqual(len(soup.find(id="bd").find_all('tbody')[0].find_all('tr')), 3)
Pues si se queja pylint es que tendrá razón, aunque siempre me sorprende que no se haya quejado antes.

2021-06-08 15:32 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
El problema es para la segunda y la tercera pista que tiene ya un salto de linea y si busco por el primer `\n` me junta todo:

![his](https://user-images.githubusercontent.com/33600064/121214150-23aeeb80-c87f-11eb-93ee-516183249214.png)

2021-06-08 16:15 UTC, emartinm commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
Al trocear el fichero de pistas usando el separador `@@@new hint@@@`, elimina espacios en blanco por la izquierda de cada trozo con `lstrip()` para quitar los saltos de línea que puedan haber quedado antes del número

2021-06-08 16:32 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
vale, había hecho algo asi, pero igual uso mas variables
![his](https://user-images.githubusercontent.com/33600064/121223370-bfdcf080-c887-11eb-9aeb-2c05fc4cc820.png)

ahora lo modifico

2021-06-08 17:23 UTC, emartinm commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
Sí, yo creo que debería salir más sencillo

2021-06-08 17:24 UTC, emartinm commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
A todo esto, las tuplas en `hints` deberían ser `(int, str)`, no `(str, str)`

2021-06-08 17:24 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
> Al trocear el fichero de pistas usando el separador `@@@new hint@@@`, elimina espacios en blanco por la izquierda de cada trozo con `lstrip()` para quitar los saltos de línea que puedan haber quedado antes del número

Pues `lstrip()` no me funciona..

```
hints_list = hints_str.split(hint_separation)
for hint in hints_list:
        hint.lstrip("\n")
```

si `hints_list = ['3\r\nEs **importante** consultar las tablas `Club` e `Inversiones`\r\n', '\r\n5\r\nEl resultado debe proyectar las siguientes filas:\r\n * Nombre renombrado a "Name"\r\n * Sede renombrado a "Address"\r\n', '\r\n10\r\nLa consulta debe tener un aspecto como el siguiente:\r\n    SELECT Club.Nombre AS Name, Club.Sede AS Address\r\n    FROM Club JOIN Inversiones ON Club.ID = Inversiones.Club\r\n    WHERE Club.Sede = ...... AND ......']` por cada elemento se deberia eliminar el primer `\n`.

Pero creo que no lo elimina porque hay un `\r` delante, y creo que se debe poner todo los caracteres que hay delante del que carácter que quieres eliminar, que he probado a eleminar `\r\n` en vez de `\n` y si lo hace

2021-06-08 17:35 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
lo he probado en una pagina y parece que es eso, hay que poner todos los caracteres que hay delante del que quieres eliminar 
![his](https://user-images.githubusercontent.com/33600064/121231298-8957a380-c890-11eb-9c9f-01dfe6764f77.png)

2021-06-08 17:46 UTC, emartinm commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
Usa `lstrip()` sin argumentos para que tome todos los posibles blancos (espacios, saltos de línea, tabuladores): https://docs.python.org/3/library/stdtypes.html#str.lstrip. Creo que eso hará que funcione en Windows y Linux.

2021-06-08 18:02 UTC, Tamiflu9 commented on lsql/judge/parse.py
> +        elem_x = elem.split('\r\n')
Ah vale, no sabia que lo reconocía así también los saltos de línea, pensé que era solo para los espacios. Ya funciona.

2021-06-08 18:35 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +            setattr(problem, 'hints_info', hint_list)
En teoría aquí tras guardar el problema ya debería tener las pistas no?

![his](https://user-images.githubusercontent.com/33600064/121238247-31249f80-c898-11eb-8990-122c472180ae.png)

No se porque me dice que el `kwargs` de las señales me dice que no tiene el atributo `hints_info`, si al probarlo si que me guarda las pistas y todo

![hjfc](https://user-images.githubusercontent.com/33600064/121238368-51ecf500-c898-11eb-8766-11019f22f593.png)

2021-06-08 18:43 UTC, emartinm commented
Kwargs no es directamente el objeto Problem, es un diccionario que almacena
ese objeto y más cosas. Revisa otras señales para ver cómo se accede.

2021-06-08 20:15 UTC, Tamiflu9 commented
> Kwargs no es directamente el objeto Problem, es un diccionario que almacena ese objeto y más cosas. Revisa otras señales para ver cómo se accede.

si, si yo accedo con :` kwargs['instance'].hints_info`
![kw](https://user-images.githubusercontent.com/33600064/121251307-02fa8c00-c8a7-11eb-8b08-1613ac3aee7e.png)

2021-06-08 20:36 UTC, Tamiflu9 commented
Es que no entiendo porque dice que el diccionario no tiene el atributo `hints_info`. Yo puedo accerder a `problem.hints_info` :

![kw](https://user-images.githubusercontent.com/33600064/121253846-e2800100-c8a9-11eb-80fc-9209123d628b.png)

y lo que no esta haciendo entonces es pasarle esas pistas a la señal para que las guarde? si es asi no se muy como pasarselo.. llamando a las señales?

2021-06-08 21:35 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +            setattr(problem, 'hints_info', hint_list)
pero en esta traza invocas a `kwargs.hints_info`

2021-06-08 21:40 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +            setattr(problem, 'hints_info', hint_list)
Realmente no acabo de entender si tu problema es que te salta esta excepción o que el test no cumple los asertos. En el caso del test en el que compruebas que el objeto después de `clean()` tiene el parámetro temporal `hints_info`, creo que es mejor hacerlo de otra manera. Realmente lo que interesa comprobar es que al cargar un problema desde un ZIP se almacenan los objetos `Hint` adecuados, no que se establezca ese atributo dinámico que es el medio para conseguir el fin que buscamos. Mejor comprueba el fin, es decir, que para cada problema cargado con un ZIP válido se crean los objetos `Hint` pertinentes.

2021-06-08 22:20 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +            setattr(problem, 'hints_info', hint_list)
> pero en esta traza invocas a `kwargs.hints_info`

Si pero porque ahi `kwargs` es `kwargs['instance']`. A la función que guarda las pistas le paso directamente `kwargs['instance']` :

```
def save_hints(**kwargs**):
    """Create the hints of a problem an save them"""
    for elem in **kwargs.hints_info**:
        num_sub = elem[0]
        description = elem[1]
        hint = Hint(text_md=description, problem=kwargs, num_submit=num_sub)
        hint.save()


@receiver(post_save, sender=SelectProblem)
def save_hints_select_problem(sender, **kwargs):
    """save Hints of a SelectProblem"""
    logger.debug('Signal post_save for %s %s', str(sender), str(kwargs['instance']))
    if hasattr(kwargs['instance'], 'hints_info'):
        save_hints(**kwargs['instance']**)
```

2021-06-08 22:24 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +            setattr(problem, 'hints_info', hint_list)
> Realmente no acabo de entender si tu problema es que te salta esta excepción o que el test no cumple los asertos. En el caso del test en el que compruebas que el objeto después de `clean()` tiene el parámetro temporal `hints_info`, creo que es mejor hacerlo de otra manera. Realmente lo que interesa comprobar es que al cargar un problema desde un ZIP se almacenan los objetos `Hint` adecuados, no que se establezca ese atributo dinámico que es el medio para conseguir el fin que buscamos. Mejor comprueba el fin, es decir, que para cada problema cargado con un ZIP válido se crean los objetos `Hint` pertinentes.

Si solo hago el `clean()` y luego compruebo su en `Hint` hay alguna pista, me devuelve 0 pistas. Si hago el `save()` del problema me dice que el atributo no existe en el diccionario. Por eso habia cogido `problem.hints_info` qu eahi al menos si las guarda bien.

2021-06-08 22:33 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +            setattr(problem, 'hints_info', hint_list)
vale creo que ya he encontrado el fallo

2021-06-09 10:23 UTC, emartinm commented on lsql/judge/parse.py
> +        hint_tupla = hint_lstrip.split(sep='\n', maxsplit=1)
Los nombres de variable en inglés, p.ej. `hint_tuple_list` y mejor junta estas dos operaciones en una:

    hint.lstrip().split(sep='\n', maxsplit=1)

2021-06-09 10:30 UTC, emartinm commented on lsql/judge/signals.py
> +def save_hints(kwargs):
`kwargs` es el nombre de los parámetros que almacenan *keyword arguments* y permiten aceptar varios parámetros dinámicamente. Tu función `save_hints` realmente solo recibe el problema, así que mejor pasa el problema: 
 
      def save_hints(problem):

2021-06-09 11:17 UTC, Tamiflu9 commented on lsql/judge/signals.py
> +def save_hints(kwargs):
Con `problem` te refieres a `kwargs['instance']` ? porque eso es lo que tenía antes y me daba fallo al hacer los tests, que decía que no estaba el atributo `hints_info` y por eso le paso todo el `kwargs`

2021-06-09 11:18 UTC, Tamiflu9 commented on lsql/judge/signals.py
> +def save_hints(kwargs):
o que cambie solo el nombre del argumento que le paso a la función?

2021-06-09 11:31 UTC, emartinm requested changes

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/signals.py
> +    for elem in kwargs['instance'].hints_info:
Más compacto:

    for num_sum, description in problem.hints_info

(suponiendo que pasas problem como parámetro)

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        self.assertEqual(hints.count(), 3)
Estos asertos se deben hacer por cada `problem`, donde están se comprueban únicamente para el último problema que será `discriminant`

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select = SelectProblem(zipfile=zip_select_path)
por qué no creas la colección antes y la pasas como parámetro de constructor con 

    SelectProblem(zipfile=..., collection=collection)

así te ahorras dentro del bucle lo de

    problem.collection = collection

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        """Test to wrong loaded zips"""
Test to check that ZIP files with wrong hints.md file raise ValidationError

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/tests/test_languages.py
> +        problem.clean()
Podías revertir del todo los cambios en este fichero? Es muy raro tener dos problemas y que se llamen `problem` y `problem3`. Estaba mejor antes.

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        hints_expected3 = (10, 'descripcion pista 3')
Añade una pista que tenga varias líneas para probarlo también, por ejemplo una entre la 5 y la 10 y que sea algún markdown válido como:

    Ten en **cuenta** que:
     * debes seleccionar las tablas
     * debes elegir cuidadosamente las columnas

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
Por completitud prueba 2 ZIP erróneos más:

A) Uno en el que el número de envíos ni siquiera es un entero, por ejemplo `cinco`:

    3
    descripcion pista 1
    @@@new hint@@@
    cinco
    descripcion pista 2
    @@@new hint@@@
    10
    descripcion pista 3

B) Otro en el que la pista está vacía pero tiene espacios y saltos de línea:

    3
    descripcion pista 1
    @@@new hint@@@
    5
        
           
                
    @@@new hint@@@
    10
    descripcion pista 3

2021-06-09 11:31 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        hints_expected3 = (10, 'descripcion pista 3')
Es decir, un fichero `hints.md` tal que:

    3
    descripcion pista 1
    @@@new hint@@@
    5
    Ten en **cuenta** que:
     * debes seleccionar las tablas
     * debes elegir cuidadosamente las columnas
    @@@new hint@@@
    10
    descripcion pista 3

2021-06-09 11:34 UTC, emartinm commented on lsql/judge/signals.py
> +def save_hints(kwargs):
En serio si invocas a `save_hints(kwargs)` y dentro accedes a `kwargs['instance'].hint_list` entonces funciona bien, pero si invocas a `save_hints(kwargs['instance'])` ese objeto que recibe no tiene `hint_list`? 

Realmente no debería haber ninguna diferencia entre una cosa y otras porque son equivalentes, no?

2021-06-09 14:57 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
> B) Otro en el que la pista está vacía pero tiene espacios y saltos de línea:
> 
> ```
> 3
> descripcion pista 1
> @@@new hint@@@
> 5
>     
>        
>             
> @@@new hint@@@
> 10
> descripcion pista 3
> ```

No consigo que el test pase por esta excepción.. Que al cargar el problema si me salta el mensaje de error pero en el test me salta que no hay mensaje de error :

![fail](https://user-images.githubusercontent.com/33600064/121378367-6cc87380-c943-11eb-907b-61b8024fe4a7.png)

Para comprobar que la pista no sean saltos de lineas he usado `isspace()`. No he encontrado otra opción

```
description = hint_tuple_list[1]
        if description == '' or description.isspace():
            raise ZipFileParsingException('Hint description cannot be empty in hints.md')
```

2021-06-09 16:00 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
comprueba que `description.strip()` no es vacío (recuerda que strip te quita todos los blancos: espacios, tabuladores, saltos de línea)

2021-06-09 16:43 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
si si eso lo he probado, y si que entra en ese `if` si metes una pista con varios saltos de linea, pero no se porque al hacer los tests justo es ultimo que me habías dicho no pasa..

2021-06-09 16:46 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
Ponte `print` para ver exactamente qué cadena es el que llega para hacerte fallar el test, porque si no es muy difícil depurar. En este caso fallar el test es no lanzar excepción y el sistema da muy poca información.

2021-06-09 16:49 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
O mejor aún usa `print(repr(description))` para ver expresamente los caracteres especiales

2021-06-09 16:57 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
la cadena esta bien, sería `['']` que es vacío

2021-06-09 17:05 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
La cadena de descripción que te llega no puede tener corchetes, no?

2021-06-09 17:06 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
Yo me refería a ver la cadena que te llega antes de hacer `strip`. Exactamente qué contiene el fichero `hints.md` del ZIP que estás usando para cargar el problema y que tiene esa pista vacía?

2021-06-09 17:25 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
no, no tiene corchetes, eso lo he añadido yo.

al hacer:

```
print(hint_tuple_list)
hint_tuple_list[1].strip()
print(hint_tuple_list)
```
lo que imprime es:
```
['5\r', '\r\n\r\n\r\n\r\n']
['5\r', '\r\n\r\n\r\n\r\n']
```

2021-06-09 17:28 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
Pues si la descripción de una pista es `'\r\n\r\n\r\n\r\n'` eso es una pista vacía y deberías detectarlo como tal. Cuando hagas `strip` se quedará como `''` y lo deberías detectar.

2021-06-09 17:28 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
si hago:
```
print(repr(description))
print(repr(description.strip()))
```

me imprime:
```
'\r\n\r\n\r\n\r\n'
''
```

2021-06-09 17:30 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
A todo esto, las cadenas en Python son inmutables. Es decir, que `strip()` no modifica la cadena original sino que **devuelve** la cadena resultante de eliminar blancos. No sé si esto es lo que te está pasando, pero si estabas entendiendo las cadenas de Python como mutables entonces te tenían que estar dando problemas en muchos más lugares.

2021-06-09 18:14 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
Me puedes pegar el código que usas para detectar cuándo la descripción está vacía (módulo blancos) y así lanzar la excepción?

2021-06-09 18:30 UTC, Tamiflu9 commented on lsql/judge/tests/test_hint.py
> +        select_description = SelectProblem(zipfile=zip_select_description_path)
Ya esta solucionado.. el problema era yo, que he guardado mal el fichero de pistas y no había puesto el separador `@@new_hint@@` y no me había dado cuenta y estaba juntado la descripción de la pista vacía con la pista siguiente. Ya te lo vuelvo a subir

2021-06-09 19:31 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        function.collection = collection
Esto quítalo porque ya lo has puesto al crear el objeto

2021-06-09 19:47 UTC, emartinm requested changes
Propongo un bucle para testear los problemas DML...Discriminant, que el código es idéntico, y alguna mejora menor o erratas.

También tengo dudas sobre los ficheros:
* lsql/judge/tests/zip_files/espacios.zip 
* lsql/judge/tests/zip_files/prueba.zip 

No se usan en los tests, verdad? Deberían quitarse.

Pero vamos, que esto ya está :grinning:

2021-06-09 19:47 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        dml.clean()
No entiendo bien por qué has expandido el bucle que tenías antes, que estaba bien. Mejor vuelve a hacer el bucle para probar DML, Function, Proc, Trigger y Discriminant en 12 líneas en lugar de 60

2021-06-09 19:47 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +    def test_to_long_hint(self):
mejor algo como `test_long_hint`

2021-06-09 19:47 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +    def test_whit_wrong_zips(self):
`test_with_wrong_zips`

2021-06-09 19:47 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        dml.clean()
Los asertos los tienes que hacer **dentro** del bucle, claro

2021-06-09 19:47 UTC, emartinm commented on lsql/judge/tests/test_hint.py
> +        """Test to check if hints.md is loaded correctly fro SelectProblem"""
`""" Test to check if hints.md is loaded correctly to a SelectProblem. It checks both hints with one line and hints with several lines """`

2021-06-09 20:12 UTC, Tamiflu9 commented
Ah claro si, si con meter los asertos dentro del bucle valía. Y los zips esos eran de prueba pero no se usan ya, los he borrado y ya he modificado lo demás. Paso los test y el pylint otra vez por si acaso y hago otro commit.

2021-06-09 20:29 UTC, merged