informar de logros
emartinm/lsql pull request #88
Opened 2021-06-10 19:03 UTC by Tamiflu9

se vería así para varios logros:

![lo](https://user-images.githubusercontent.com/33600064/121582227-0ae53800-ca2f-11eb-89b1-b10f243d6b28.png)

asi para un logro:

![l](https://user-images.githubusercontent.com/33600064/121582365-3536f580-ca2f-11eb-9c21-5cb51c31cbc3.png)

y asi sin ninguno:

![s](https://user-images.githubusercontent.com/33600064/121582415-4849c580-ca2f-11eb-9e6a-5874d687c15f.png)

2021-06-10 19:26 UTC, emartinm commented
A mi me gustaría el mensaje de logros más integrado en el texto, tal y como mencionaba en el issue #65:

_¡Enhorabuena¡ Tu código SQL ha generado los resultados esperados. Además, con este envío acabas de conseguir los     logros "Experto en SELECT" y "Rey de los HAVING". Accede a la página Mis Logros para más información._

_¡Enhorabuena¡ Tu código SQL ha generado los resultados esperados. Además, con este envío acabas de conseguir el logro    "Experto en SELECT". Accede a la página Mis Logros para más información._

Revisa también el texto para las comas y porque la frase que muestras parece algo redundante. Adicionalmente, me parece feo que la ventana ocupe tanto hueco vacío incluso cuando no hay logros. Cuando no haya nada que decir de logros, no se debería ocupar espacio adicional y las ventanas se deberían mostrar tal y como estaban antes del PR.

Por otro lado, esto tiene que funcionar con cualquier otro envío que no sea AC, ya que hay un logro que depende únicamente de los envíos y que podrías obtener con un WA, RE, TLE, VE o incluso IE. ¿Esto lo tienes en cuenta? Añade alguna captura para documentarlo.

2021-06-10 19:27 UTC, emartinm commented
A mi me gustaría el mensaje de logros más integrado en el texto, tal y como mencionaba en el issue #65:

_¡Enhorabuena¡ Tu código SQL ha generado los resultados esperados. Además, con este envío acabas de conseguir los     logros "Experto en SELECT" y "Rey de los HAVING". Accede a la página Mis Logros para más información._

_¡Enhorabuena¡ Tu código SQL ha generado los resultados esperados. Además, con este envío acabas de conseguir el logro    "Experto en SELECT". Accede a la página Mis Logros para más información._

Revisa también el texto para las comas y porque la frase que muestras parece algo redundante. Adicionalmente, me parece feo que la ventana ocupe tanto hueco vacío incluso cuando no hay logros. Cuando no haya nada que decir de logros, no se debería ocupar espacio adicional y las ventanas se deberían mostrar tal y como estaban antes del PR.

Por otro lado, esto tiene que funcionar con cualquier otro envío que no sea AC, ya que hay un logro que depende únicamente de los envíos y que podrías obtener con un WA, RE, TLE, VE o incluso IE. ¿Esto lo tienes en cuenta? Añade alguna captura para documentarlo.

2021-06-10 20:00 UTC, emartinm reviewed
Me ha gustado mucho el test de unidad, es muy completo. De hecho lo puedes simplificar porque creo que compruebas cosas fuera de tu obligación (solo debes comprobar el mensaje).

Propongo algunos cambios en el mensaje:
 - el JSON se extiende únicamente con un mensaje de texto que se genera en el servidor
 - ese mensaje junta todo en una línea, no en varias
 - si te ayuda, genera esa cadena usando una plantilla en lugar de concatenar cadenas directamente en Python, que siempre queda un poco cutre

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/models.py
> +    """ Default values for name and description attributes in AchievementDefinitionAchievementDefinition """
Qué es esto?

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/models.py
> +                return True
Si ahora esto devuelve un booleano se debería explicar en el comentario de la función (lo mismo para el resto de funciones `check_and_save()`)

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/static/judge/js/submit.js
> +    }
Esto lo podrás quitar cuando en `myJson.achievements` te llegue toda la frase para pegar

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/static/judge/js/submit.js
> +          show_modal(myJson.title, myJson.message, myJson.sentence_achievements, myJson.names);
Solo un parámetro

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/templates/problem.html
> +          <div id="info_achieve">
Elimina al menos estos dos últimos elementos `modal_name_achieve` y `info_achieve`. No me parece mal que la frase que te llegue la pongas en `modal_sentence_achieve` y quede separada, pero que no ocupe nada de espacio vertical si no tiene texto.

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/templates/problem.html
> +          {% translate "Mis logros" %}</a>{% translate " para obtener mas información." %}
Para simplificar, mete esta frase junto con todo lo demás en el servidor y que llegue en `myJson.achievements`

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        """Test to show correct message when obtain an achievement"""
Test to check that submissions receive correct achievement messages

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/views.py
> +                names.append(list(ach.name.values()))
Los logros son multidioma, así que aquí tendrás que coger el nombre del logro del idioma actual. Mira el código que genera la página de logros (o pregunta a @ivarui01 si no lo ves claro)

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/views.py
> +        data['sentence_achievements'] = 'Además con este envío has conseguido el siguiente logro: '
falta el soporte multidioma

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/views.py
> +    if len(data['names']) == 0:
La manera más pythonica de comprobar que una cadena no es vacía es con:

    if data['names']:
        # La cadena no es vacía

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        vacio = []
En español

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        # The user makes a submission and problem and obtain one achievement
The user submits one solution and obtains the first achievement

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        self.assertEqual(obtained_achieve.count(), 1)
Lo que hay que probar es que el JSON tiene el mensaje adecuado, no que se ha salvado el logro (eso es problema de otro)

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        self.assertEqual(response.json()['veredict'], VeredictCode.VE)
Incluso esto te lo puedes quitar porque no es tu cometido

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        # The user makes another submission and does not obtain an achievement
....submits a new solution and does not receive any achievement

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        self.assertEqual(obtained_achieve.count(), 1)
Fuera

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        self.assertEqual(response.json()['veredict'], VeredictCode.VE)
Fuera

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        ach_type = NumSolvedTypeAchievementDefinition(name={"es": 'Es select'},
Mueve este logro junto a los demás, para que estén juntos y al revisar el código se sepa qué hay

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        self.assertEqual(obtained_achieve.count(), 3)
No es tu cometido

2021-06-10 20:00 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        self.assertEqual(response.json()['veredict'], VeredictCode.AC)
Tampoco es tu cometido

2021-06-10 20:57 UTC, Tamiflu9 commented
> Por otro lado, esto tiene que funcionar con cualquier otro envío que no sea AC, ya que hay un logro que depende únicamente de los envíos y que podrías obtener con un WA, RE, TLE, VE o incluso IE. ¿Esto lo tienes en cuenta? Añade alguna captura para documentarlo.

Si, por ejemplo:

se hace dos envíos de tipo RE también:
![errrrrr](https://user-images.githubusercontent.com/33600064/121595496-a205bc00-ca3e-11eb-96a5-f4a0184d1091.png)
![eeee](https://user-images.githubusercontent.com/33600064/121595492-a16d2580-ca3e-11eb-9c05-82e6cd7303bc.png)

si se hace dos envíos y consigues el logro:
![lo](https://user-images.githubusercontent.com/33600064/121595799-f1e48300-ca3e-11eb-9289-cd97b12e3031.png)
![s](https://user-images.githubusercontent.com/33600064/121595794-f0b35600-ca3e-11eb-8a2c-b8fee655a45d.png)

2021-06-10 21:03 UTC, emartinm commented
> Por otro lado, esto tiene que funcionar con cualquier otro envío que no sea AC, ya que hay un logro que depende únicamente de los envíos y que podrías obtener con un WA, RE, TLE, VE o incluso IE. ¿Esto lo tienes en cuenta? Añade alguna captura para documentarlo.

Me refería a capturas de pantalla del popup diciendo "Error en ejecución" con el mensaje de "has conseguido logros", perdona si no he sido claro :smiley:

2021-06-10 22:01 UTC, emartinm commented
Perfecto, entonces consigue que toda la información de los logros que aparece en la ventana sea una única frase (y no 3 `div`) que se genere tal cual en el servidor y estaría listo. Ah, y que ese trozo no ocupe ningún espacio vertical cuando es vacío.

2021-06-11 09:08 UTC, emartinm commented on lsql/judge/views.py
> +        data['sentence_achievements'] = 'Además con este envío has conseguido el siguiente logro: '
Y para los plurales no lo hagas a mano, usa el soporte de Django para traducción con plurales: https://docs.djangoproject.com/en/3.2/topics/i18n/translation/#pluralization

2021-06-11 11:34 UTC, Tamiflu9 commented on lsql/judge/models.py
> +    """ Default values for name and description attributes in AchievementDefinitionAchievementDefinition """
Ah se habrá pegado sin querer cuando buscaba `AchievementDefinition`, ya esta borrado

2021-06-11 14:18 UTC, Tamiflu9 commented
Me he creado la plantilla `achievement_notice.html`
![html](https://user-images.githubusercontent.com/33600064/121700876-9cf14d00-cad0-11eb-8034-5788d2ba09d2.png)

en `views.py` en la función de submit ya tengo la lista con los objetos `AchievementDefinition` y llamo al `render_to_string()` con esta lista:
![viewa](https://user-images.githubusercontent.com/33600064/121699392-2c95fc00-cacf-11eb-9895-f96e6e43d410.png)

en `submit.js` al tener el otro parámetro `notify`, para saber cuando ocultar o no el mensaje y creo que así no ocupará espacios
![submit](https://user-images.githubusercontent.com/33600064/121699388-2bfd6580-cacf-11eb-9300-bef1f68ccbee.png)

en problem se quedaría asi la ventana emergente:
![problem](https://user-images.githubusercontent.com/33600064/121699393-2c95fc00-cacf-11eb-8c9e-2b0a7a14cccb.png)

no se si me falta algo mas, crear una url para `achievement_notice.html` o no hace falta?

2021-06-11 15:27 UTC, emartinm commented
> Me he creado la plantilla achievement_notice.html. He añadido también lo de los plurales

1. ¿La pluralización está funcionando bien? El que parece que repites "el" y que "siguiente" siempre está en singular.
2. La frase que propongo no tiene dos puntos y son los nombres entre comillas separados por comas salvo el último elemento que está separado por "y". Por ejemplo: _Además, con este envío acabas de conseguir los logros "Experto en SELECT", "Bailarín de JOIN" y "Rey de los HAVING". Accede a la página Mis Logros para más información._
3. Mejor que un campo 'notify' para mostrar o no, hagamos que el campo ''achievements" (que se llame así mejor que "sentence_achievements") exista únicamente cuando se consiguen logros. Si existe, se pone; si no existe, se oculta.
4. No veo por qué puede hacer falta una URL para la plantilla.
5. No pongas `if len(X) > 0:` sino `if X:` que queda más Python
6. Para añadir una 's' en los plurales, que es lo más común, solo necesitas `{{ ach|pluralize }}`. Solo tienes que añadir más argumentos cuando la pluralización cambia un poco más

2021-06-11 16:23 UTC, Tamiflu9 commented
> 4. No veo por qué puede hacer falta una URL para la plantilla.

porque me sale este error, que en la tarea de las pistas creo que era por problemas con la url
![consola](https://user-images.githubusercontent.com/33600064/121717994-17769880-cae2-11eb-95f4-3476fd33b3fd.png)

2021-06-12 10:28 UTC, emartinm commented
> porque me sale este error, que en la tarea de las pistas creo que era por problemas con la url

Si revisas con cuidado la traza, parece que el problema está al renderizar una plantilla llamada `notifiy.html` (no parece ser la misma que la `achievement_notice.html` que adjuntaste ayer) que debe contener una enlace a la ruta `achievements`. Es al tratar de resolver esa ruta a partir de su nombre cuando falla.

2021-06-12 12:04 UTC, Tamiflu9 commented
Ya si si es que cambie el nombre de todo, por si hacia algo, pero sale el mismo error. No se que problema tiene con la plantilla
![err](https://user-images.githubusercontent.com/33600064/121775293-05026a80-cb87-11eb-93ac-cd4c8c5beaaa.png)

2021-06-12 12:23 UTC, emartinm commented
Comprueba que el argumento que usas al generar la URL es adecuado. En el mensaje aparece algo raro como `'('',)'` que no parece un identificador de usuario demasiado válido (debía ser algo puramente numérico). Ponte `prints` para entender bien qué le está llegando.

2021-06-12 15:38 UTC, Tamiflu9 commented
ya está solucionado, lo que no se es porque ahora no me reconoce el html y lo interpreta como una cadena:
![ee](https://user-images.githubusercontent.com/33600064/121781425-ec08b200-cba4-11eb-8206-1d8f451e31f2.png)

2021-06-12 17:57 UTC, emartinm commented
> ya está solucionado, lo que no se es porque ahora no me reconoce el html y lo interpreta como una cadena:
> ![ee](https://user-images.githubusercontent.com/33600064/121781425-ec08b200-cba4-11eb-8206-1d8f451e31f2.png)
> 

Cuando añades cosas a una página HTML, puedes añadir texto (como parece ser el caso) o directamente elementos HTML (lo que tendrías que hacer ahora). Mira cómo se maneja el feedback del JSON, porque será parecido.

Por otro lado, trata de ceñirte un poco más a la frase propuesta.

2021-06-13 18:47 UTC, Tamiflu9 commented
Tengo dos dudas, una no se muy bien porque al poner lo del `{% blocktranslate %}` no me coge lo de los plurales. 
![ee](https://user-images.githubusercontent.com/33600064/121818575-547c8f80-cc88-11eb-8733-59831c003e84.png)


Y la otra, no se muy bien como listar bien lao logros separados de comas y eso, que intento hacer un `while` o recorrer la lista hasta el penúltimo elemento pero nada y no se si se podría hacer una lista así (la frase estaría mal por lo anterior, si no se podría cambair a algo más genérico como 'Además has conseguido estos logros: '):
![err](https://user-images.githubusercontent.com/33600064/121818574-534b6280-cc88-11eb-9289-d515e38725d5.png)

2021-06-13 19:57 UTC, emartinm commented
Desconocía que pudiese haber una interacción extraña entre traducción y pluralización... Para simplificar, mételo en dos frases traducidas dependiendo de la cantidad:

    if `varios logros`:
        Frase "Además, con este envío has conseguido los logros "
    else:
        Frase "Además, con este envío has conseguido el logro "

Para hacer la frase todo junto usa el mismo bucle `for` sin crear una lista `<ul>` con algo de lógica adicional para poner una coma al final de cada logro si quedan más de dos, y un "y" si queda exactamente uno. Para saber en qué posición estás de la lista puedes usar las variables `forloop` de https://docs.djangoproject.com/en/3.2/ref/templates/builtins/#for

2021-06-13 20:35 UTC, Tamiflu9 commented
quedaría así para un logro:

![err](https://user-images.githubusercontent.com/33600064/121821170-98c35c00-cc97-11eb-946a-7b97642af193.png)

y así para varios logros:

![ee](https://user-images.githubusercontent.com/33600064/121821167-97922f00-cc97-11eb-95b0-044d55a8fb18.png)

2021-06-13 21:19 UTC, Tamiflu9 commented
Se que las comas están mal, lo he arreglado:

![html](https://user-images.githubusercontent.com/33600064/121822138-bd223700-cc9d-11eb-8937-a5dbf0bab969.png)
![consola](https://user-images.githubusercontent.com/33600064/121822141-bdbacd80-cc9d-11eb-89c7-54b9b44e65c1.png)

2021-06-13 22:03 UTC, emartinm commented on lsql/judge/views.py
> +    names = []
nombre con más sentido: `obtained_achievements`

2021-06-13 22:04 UTC, emartinm commented on lsql/judge/views.py
> +    """Check if the user get some achievement annd return a list of Achievementes obtained"""
*and*

2021-06-13 22:05 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr "Access the "
the webpage

2021-06-13 22:10 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +            self.assertEqual('no exixte', msg)
El aserto "no exixte" = "no exixte" es poco útil. Lo que querrás comprobar es que `'achievements' not in response.json()` con un aserto `assertNotIn`.

2021-06-13 22:11 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +            self.assertEqual('no exixte', msg)
Mismo comentario de antes: `assertNotIn`

2021-06-13 22:15 UTC, emartinm commented
He detectado una errata, una variable con nombre más concreto y un par de asertos mejorables; pero el PR está muy bien.

2021-06-14 08:27 UTC, emartinm approved these changes
Perfecto! He encontrado alguna errata menor, pero ya me encargo yo de ello.

2021-06-14 08:35 UTC, emartinm requested changes
El soporte en TravisCI para detectar errores parece no estar funcionando correctamente y hasta que no lo he visto manualmente no me he dado cuenta de que el test de unidad estaba fallando. 

Ya que tenía que hacer la revisión, he añadido las dos erratas que te he comentado antes.

2021-06-14 08:35 UTC, emartinm commented on lsql/judge/tests/test_submit.py
> +        self.assertNotIn('achievements', response.json)
Estaba a punto de aceptar el PR pero en https://travis-ci.com/github/emartinm/lsql/builds/228830582 he visto que el test falla aquí y que no se consigue el 100% de cobertura. Creo que solo te faltan unos paréntesis en `response.json()` pero revísalo.

2021-06-14 08:35 UTC, emartinm commented on lsql/locale/en/LC_MESSAGES/django.po
> +msgstr " page for more information."
" for more information"

2021-06-14 08:35 UTC, emartinm commented on lsql/judge/views.py
> +    """Check if the user get some achievement and return a list of Achievementes obtained"""
obtained achievements

2021-06-14 09:02 UTC, emartinm approved these changes
100% en tests!

2021-06-14 09:02 UTC, merged